//! Procedural macros for [`bstack_raii`](https://github.com/williamwutq/bstack).
//!
//! Three entry points, all documented in `RAII.md` at the repository root:
//!
//! * [`macro@bstack_block`] — attribute macro. Turns an ergonomic struct into a
//!   parallel `#[repr(C, packed)]` on-disk representation plus generated
//!   accessors, `BStackDrop`, `BStackCast`, and (for `(rc, weak)`)
//!   `BStackWeakable` impls.
//! * [`bstack_move`] — function-like macro. Destructures a `BStackOwned<X>`,
//!   transferring ownership of every field out as a tuple of typed handles.
//! * [`bstack_cast`] — function-like macro. Direction-inferring typed/untyped
//!   handle conversion.

use proc_macro::TokenStream;

mod block;

/// `#[bstack_block]` — generate the on-disk layout and typed handle machinery.
///
/// # Arguments
///
/// `#[bstack_block(rc)]` / `#[bstack_block(rc, weak)]` select the refcount mode.
/// `tag = "…"` / `ctrl_tag = "…"` override the generated tags (see below), and
/// `allow_long_tag` silences the truncation warning for an over-long override.
/// All are optional and may appear in any order.
///
/// # Generated items (for `struct X { .. }`)
///
/// * `struct X(BStackRange)` — the typed handle, and `struct XOnDisk`
///   (`#[repr(C, packed)]`, `Pod`) — the on-disk payload. `#[bstack_owned]` /
///   `#[bstack_strong]` / `#[bstack_weak]` / `#[bstack_ref]` fields lower to a
///   `u64` offset; un-annotated fields are stored inline (and must be `Pod`).
///   `(rc)` injects an inline `refcount`; `(rc, weak)` injects a `ctrl`
///   back-pointer and emits an `XOnDiskRef` control block.
/// * `impl BStackCast / BStackBlock / BStackDrop`, plus `BStackShared`
///   (`rc` / `rc, weak`), `BStackWeakable` (`rc, weak`), and `BStackMove`
///   (plain blocks — the `bstack_move!` target).
/// * Field accessors, `set_<field>` for weak fields, and a `new` constructor.
///
/// # EightCC tag generation
///
/// Each block's [`EightCC`](../bstack_raii/struct.EightCC.html) is an 8-byte tag
/// = a **readable ASCII prefix** over the first bytes, followed by the tail of a
/// **64-bit FNV-1a hash** of `crate_name ++ "\0" ++ type_name` (little-endian).
/// Every hash-tail byte has its high bit set, so it lands in the non-printable
/// range and reads as clearly-not-a-name in a hex dump. The hash keeps distinct
/// types apart even when their prefixes collide, and is deterministic (stable
/// across builds/versions) so it is safe as on-disk ABI.
///
/// The prefix is derived from the type name: initials of the camel-case words
/// (≥ 2 words), or the de-voweled single word, clamped to 2–5 bytes. Override it
/// with `tag = "PREFIX"` (0–8 bytes; fewer than 8 leaves room for hash, exactly
/// 8 is a fully manual tag, over 8 warns and truncates). The control block's tag
/// is the data tag with its prefix **lowercased**, or an explicit `ctrl_tag`.
#[proc_macro_attribute]
pub fn bstack_block(args: TokenStream, item: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(item as syn::ItemStruct);
    match block::expand(args.into(), input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// `bstack_move!(x)` — transfer every field out of a `BStackOwned<X>`.
///
/// Expands to a block that reads each field's `BStackRef`/POD value from
/// `XOnDisk` (capturing `ctrl` refs for `(rc, weak)` / weak fields first),
/// `dealloc_range`s the parent shell only, then reconstructs typed handles with
/// the allocator attached and returns them as a `Result<(..), io::Error>` tuple.
/// Callable only on `BStackOwned<X, A>`; not defined for `(rc)` / `(rc, weak)`
/// blocks. See RAII.md "`bstack_move!`".
#[proc_macro]
pub fn bstack_move(input: TokenStream) -> TokenStream {
    // The per-field destructuring is generated by `#[bstack_block]` as a
    // `BStackMove` impl on `BStackOwned<X, A>`; here we just invoke it, letting
    // type inference select the block's impl from the argument's type.
    let expr = syn::parse_macro_input!(input as syn::Expr);
    quote::quote!(::bstack_raii::BStackMove::bstack_move(#expr)).into()
}

/// `bstack_cast!(handle)` — type-checked handle conversion, direction inferred
/// from the target type.
///
/// Emits `.cast_into::<X>()` / `.into_slice()` (owned) or `.cast_as::<X>()` /
/// `.as_slice()` (borrowed) depending on whether the target is a concrete
/// `#[bstack_block]` type (downcast) or a `BStackOwnedSlice` / `BStackSlice`
/// (upcast). See RAII.md "`bstack_cast!`".
#[proc_macro]
pub fn bstack_cast(_input: TokenStream) -> TokenStream {
    "::core::todo!(\"bstack_cast! not yet implemented\")"
        .parse()
        .unwrap()
}
