//! The core block contracts: [`BStackCast`] (the downcast tag) and
//! [`BStackBlock`] (a typed handle over an on-disk block, with its recursive
//! teardown / deep-clone hooks).
//!
//! Written by hand for now; generated by the macro later. They let generic
//! runtime code (handles, `bstack_move!`) name a block's on-disk shape, tag, and
//! control block without knowing the concrete type. The refcount / weak / move /
//! embed capabilities that build on `BStackBlock` live in the sibling
//! [`rc`](crate::types::rc), [`r#move`](crate::types::r#move), and
//! [`embed`](crate::types::embed) modules.

use std::io;

use bstack::BStackRange;
use bytemuck::Pod;

use crate::BStackRaiiAllocator;
use crate::clone::ClonePlan;
use crate::primitives::EightCC;
use crate::reference::BStackRef;

/// The downcast discriminant. The returned [`EightCC`] must match the tag in a
/// block's [`crate::BlockHeader`] for a safe downcast to succeed.
pub trait BStackCast {
    fn eightcc() -> EightCC;
}

/// A typed handle over a block: a newtype around a [`BStackRange`] that knows its
/// on-disk representation and how to be recursively freed.
///
/// `OnDisk` is the generated `#[repr(C, packed)]` payload struct; it must be
/// [`Pod`] so it can be read back with `bytemuck::from_bytes`.
///
/// The `#[diagnostic::on_unimplemented]` message turns the trait-bound failure
/// that a bad *generic* instantiation produces (which the macro cannot catch, as
/// the type parameter is opaque at expansion) into a readable one — e.g. a
/// `#[bstack_owned] Vec<T>` field instantiated with `T = Vec<u32>`.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a `#[bstack_block]` / `#[bstack_enum]` type",
    label = "not a bstack block",
    note = "`#[bstack_owned]` / `#[bstack_strong]` / `#[bstack_weak]` / `#[bstack_ref]` fields \
            (and generic parameters used as them) require a block type. Primitives, `Vec`, \
            `String`, tuples and `Option` are not blocks — a nested `Vec`/`Option` or a tuple \
            needs its own named `#[bstack_block]` wrapper."
)]
pub trait BStackBlock: BStackCast + Sized {
    /// The on-disk payload layout (the generated `XOnDisk`).
    type OnDisk: Pod;

    /// Wrap a range as a typed handle (no I/O, no validation).
    ///
    /// The handle itself is a **non-owning view** — `Copy`, no [`BStackDrop`], so
    /// holding or duplicating one can never free anything. Ownership (and the
    /// obligation to free exactly once) lives only in the affine wrappers
    /// [`BStackOwned`](crate::BStackOwned) / [`crate::BStackRc`] / the
    /// `handle::*Ref` teardown tokens, none of which are `Copy`.
    ///
    /// # Safety
    /// The caller asserts `range` refers to a validly allocated block of type `T`
    /// (or will, by the time the handle is read). Nothing is checked: every
    /// accessor reads `range` as `T`'s layout, so a bogus or foreign range
    /// enables wrong-type reads. It does **not** on its own enable a free — that
    /// requires wrapping the handle in an affine owner, itself an `unsafe` step
    /// ([`BStackOwned::from_raw`](crate::BStackOwned::from_raw)). The safe ways to
    /// obtain a handle — a block constructor, `bstack_cast!`, or reading a
    /// `#[bstack_block]` field — are all bound to a real allocation.
    unsafe fn from_range(range: BStackRange) -> Self;

    /// The underlying range this handle points at.
    fn range(&self) -> BStackRange;

    /// Recursively free this block's owned children given its `range`, **without**
    /// freeing the block itself — used when the block is `#[embed]`ded (its storage
    /// is part of the parent) and by `bstack_drop` before the self-dealloc. The
    /// generated impl overrides this; the default (a **childless** block) frees
    /// nothing. Exposed on the trait — rather than as a generated inherent method —
    /// so a generic parent can recurse into a type parameter. `#[doc(hidden)]`.
    #[doc(hidden)]
    fn __bstack_drop_children<A: BStackRaiiAllocator>(
        range: BStackRange,
        allocator: &A,
    ) -> io::Result<()> {
        let _ = (range, allocator);
        Ok(())
    }

    /// Read this block's `OnDisk` and return a deep-cloned copy for a
    /// [`ClonePlan`]: owned children cloned into the plan, shared children's
    /// refcounts bumped, embedded children folded in place — *without* allocating
    /// a block for `self`. The generated `#[bstack_block]` impl overrides this
    /// with the field-aware body; the default (used by hand-written impls of a
    /// **childless** block) copies the `OnDisk` verbatim. Exposed on the trait —
    /// rather than as a generated inherent method — so a generic parent can
    /// recurse into a type parameter's clone. `#[doc(hidden)]`: an impl detail.
    #[doc(hidden)]
    fn __bstack_clone_children_inplace<A: BStackRaiiAllocator>(
        &self,
        allocator: &A,
        _plan: &mut ClonePlan,
    ) -> io::Result<Self::OnDisk> {
        let mut buf = std::vec![0u8; core::mem::size_of::<Self::OnDisk>()];
        let r = unsafe { BStackRef::<Self>::from_range(self.range()) };
        Ok(*r.read_on_disk(allocator.stack(), &mut buf)?)
    }

    /// Deep-clone this block's subtree into a [`ClonePlan`]: allocate a fresh
    /// destination block, recurse into children via
    /// [`__bstack_clone_children_inplace`](Self::__bstack_clone_children_inplace),
    /// and stage the destination payload (writes are staged, committed by the
    /// caller). Overridden by the generated impl; the default suffices for a
    /// childless block. `#[doc(hidden)]`: an impl detail.
    #[doc(hidden)]
    fn __bstack_clone_into<A: BStackRaiiAllocator>(
        &self,
        allocator: &A,
        plan: &mut ClonePlan,
    ) -> io::Result<BStackRange> {
        let od = self.__bstack_clone_children_inplace(allocator, plan)?;
        let dst = plan.alloc_raw(allocator, core::mem::size_of::<Self::OnDisk>() as u64)?;
        plan.write(dst.start(), bytemuck::bytes_of(&od).to_vec());
        Ok(dst)
    }

    /// Cross-file **teardown** of an `#[bstack_owned] Foreign<Self>` target at
    /// `offset` in the file `alloc` addresses: free the block and, recursively, its
    /// children. This is the owned-foreign field teardown the generated code calls;
    /// the capability (owning) is what `BStackBlock` provides.
    ///
    /// # Safety
    /// `offset` names a live `Self` block, in the file `alloc` addresses, exclusively
    /// owned by this foreign pointer (freed exactly once).
    #[doc(hidden)]
    unsafe fn foreign_drop<A: BStackRaiiAllocator>(alloc: &A, offset: u64) -> io::Result<()> {
        // SAFETY: forwarded to the caller's contract above.
        unsafe { crate::foreign::foreign_drop_owned::<Self, A>(alloc, offset) }
    }

    /// Cross-file **deep-clone** of an `#[bstack_owned] Foreign<Self>` target at
    /// `offset` in the file `alloc` addresses; returns the copy's offset. Available
    /// only when `Self` is itself deep-cloneable ([`TryCloneIn`](crate::TryCloneIn)).
    ///
    /// # Safety
    /// `offset` names a live `Self` block, in the file `alloc` addresses, owned by
    /// this foreign pointer.
    #[doc(hidden)]
    unsafe fn foreign_clone<A: BStackRaiiAllocator>(alloc: &A, offset: u64) -> io::Result<u64>
    where
        Self: crate::clone::TryCloneIn,
    {
        // SAFETY: forwarded to the caller's contract above.
        unsafe { crate::foreign::foreign_clone_owned::<Self, A>(alloc, offset) }
    }
}
