//! The trait contracts every `#[bstack_block]` type implements.
//!
//! Written by hand for now; generated by the macro later. They let generic
//! runtime code (handles, `bstack_move!`) name a block's on-disk shape, tag, and
//! control block without knowing the concrete type.

use std::io;

use bstack::{BStackOwnedSliceAllocator, BStackRange};
use bytemuck::Pod;

use crate::layout::EightCC;
use crate::reference::BStackRef;
use crate::teardown::BStackDrop;

/// The downcast discriminant. The returned [`EightCC`] must match the tag in a
/// block's [`crate::BlockHeader`] for a safe downcast to succeed.
pub trait BStackCast {
    fn eightcc() -> EightCC;
}

/// A typed handle over a block: a newtype around a [`BStackRange`] that knows its
/// on-disk representation and how to be recursively freed.
///
/// `OnDisk` is the generated `#[repr(C, packed)]` payload struct; it must be
/// [`Pod`] so it can be read back with `bytemuck::from_bytes`.
pub trait BStackBlock: BStackCast + BStackDrop + Sized {
    /// The on-disk payload layout (the generated `XOnDisk`).
    type OnDisk: Pod;

    /// Wrap a range as a typed handle (no I/O, no validation).
    fn from_range(range: BStackRange) -> Self;

    /// The underlying range this handle points at.
    fn range(&self) -> BStackRange;
}

/// Destructure an owned block into its typed field handles.
///
/// Implemented for `BStackOwned<X, A>` by `#[bstack_block]` (plain blocks only)
/// and invoked by the `bstack_move!` macro. It transfers ownership of every
/// field out — owned children as `BStackOwned`, refs as `BStackRef`, POD by
/// value — and frees only the parent shell. Not implemented for `(rc)` /
/// `(rc, weak)` blocks, nor (yet) for blocks with `#[bstack_strong]` /
/// `#[bstack_weak]` fields.
pub trait BStackMove: Sized {
    /// The tuple of field handles produced, in field-declaration order.
    type Fields;
    fn bstack_move(self) -> io::Result<Self::Fields>;
}

/// Implemented by refcounted blocks (`#[bstack_block(rc)]` and
/// `#[bstack_block(rc, weak)]`), i.e. any block that can be the target of a
/// `#[bstack_strong]` field.
///
/// It abstracts "drop one strong reference to a child of this type" so a
/// parent's generated teardown does not need to know whether the child is a
/// plain `(rc)` block (inline refcount, [`crate::StrongRef`]) or an
/// `(rc, weak)` block (control block, [`crate::StrongWeakRef`]). The child's own
/// `#[bstack_block]` expansion picks the right implementation.
pub trait BStackShared: BStackBlock {
    /// Drop one strong reference to a block of this type located at `data`,
    /// freeing it (and, for `(rc, weak)`, releasing the control block) when the
    /// strong count reaches zero.
    fn drop_strong_ref<A: BStackOwnedSliceAllocator>(
        data: BStackRef<Self>,
        allocator: &A,
    ) -> io::Result<()>;

    /// Resolve the raw parts of a strong handle to a child of this type at
    /// `data`: the data ref, plus the control-block range for `(rc, weak)`
    /// blocks (`None` for plain `(rc)`). Used by `bstack_move!` to rebuild a
    /// `BStackRc` for a `#[bstack_strong]` field.
    fn strong_parts<A: BStackOwnedSliceAllocator>(
        data: BStackRef<Self>,
        allocator: &A,
    ) -> io::Result<(BStackRef<Self>, Option<BStackRange>)>;
}

/// Implemented only for blocks declared `#[bstack_block(rc, weak)]`.
///
/// Its presence is what lets [`crate::BStackRc`] expose `downgrade` and
/// [`crate::BStackWeak`] exist for the type. `Control` is the generated
/// `XOnDiskRef` control-block payload holding the `strong`/`weak` counters.
/// Plain `#[bstack_block(rc)]` blocks do not implement it, so weak references to
/// them are a compile error rather than a runtime hazard.
pub trait BStackWeakable: BStackBlock {
    /// The on-disk control-block payload (the generated `XOnDiskRef`).
    type Control: Pod;
}
