//! The trait contracts every `#[bstack_block]` type implements.
//!
//! Written by hand for now; generated by the macro later. They let generic
//! runtime code (handles, `bstack_move!`) name a block's on-disk shape, tag, and
//! control block without knowing the concrete type.

use bstack::BStackRange;
use bytemuck::Pod;

use crate::layout::EightCC;
use crate::teardown::BStackDrop;

/// The downcast discriminant. The returned [`EightCC`] must match the tag in a
/// block's [`crate::BlockHeader`] for a safe downcast to succeed.
pub trait BStackCast {
    fn eightcc() -> EightCC;
}

/// A typed handle over a block: a newtype around a [`BStackRange`] that knows its
/// on-disk representation and how to be recursively freed.
///
/// `OnDisk` is the generated `#[repr(C, packed)]` payload struct; it must be
/// [`Pod`] so it can be read back with `bytemuck::from_bytes`.
pub trait BStackBlock: BStackCast + BStackDrop + Sized {
    /// The on-disk payload layout (the generated `XOnDisk`).
    type OnDisk: Pod;

    /// Wrap a range as a typed handle (no I/O, no validation).
    fn from_range(range: BStackRange) -> Self;

    /// The underlying range this handle points at.
    fn range(&self) -> BStackRange;
}

/// Implemented only for blocks declared `#[bstack_block(rc, weak)]`.
///
/// Its presence is what lets [`crate::BStackRc`] expose `downgrade` and
/// [`crate::BStackWeak`] exist for the type. `Control` is the generated
/// `XOnDiskRef` control-block payload holding the `strong`/`weak` counters.
/// Plain `#[bstack_block(rc)]` blocks do not implement it, so weak references to
/// them are a compile error rather than a runtime hazard.
pub trait BStackWeakable: BStackBlock {
    /// The on-disk control-block payload (the generated `XOnDiskRef`).
    type Control: Pod;
}
