//! The trait contracts every `#[bstack_block]` type implements.
//!
//! Written by hand for now; generated by the macro later. They let generic
//! runtime code (handles, `bstack_move!`) name a block's on-disk shape, tag, and
//! control block without knowing the concrete type.

use std::io;

use crate::BStackRaiiAllocator;
use bstack::BStackRange;
use bytemuck::Pod;

use crate::clone::ClonePlan;
use crate::layout::EightCC;
use crate::owned::BStackOwned;
use crate::reference::BStackRef;
use crate::teardown::BStackDrop;

/// The downcast discriminant. The returned [`EightCC`] must match the tag in a
/// block's [`crate::BlockHeader`] for a safe downcast to succeed.
pub trait BStackCast {
    fn eightcc() -> EightCC;
}

/// A typed handle over a block: a newtype around a [`BStackRange`] that knows its
/// on-disk representation and how to be recursively freed.
///
/// `OnDisk` is the generated `#[repr(C, packed)]` payload struct; it must be
/// [`Pod`] so it can be read back with `bytemuck::from_bytes`.
///
/// The `#[diagnostic::on_unimplemented]` message turns the trait-bound failure
/// that a bad *generic* instantiation produces (which the macro cannot catch, as
/// the type parameter is opaque at expansion) into a readable one — e.g. a
/// `#[bstack_owned] Vec<T>` field instantiated with `T = Vec<u32>`.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a `#[bstack_block]` / `#[bstack_enum]` type",
    label = "not a bstack block",
    note = "`#[bstack_owned]` / `#[bstack_strong]` / `#[bstack_weak]` / `#[bstack_ref]` fields \
            (and generic parameters used as them) require a block type. Primitives, `Vec`, \
            `String`, tuples and `Option` are not blocks — a nested `Vec`/`Option` or a tuple \
            needs its own named `#[bstack_block]` wrapper."
)]
pub trait BStackBlock: BStackCast + BStackDrop + Sized {
    /// The on-disk payload layout (the generated `XOnDisk`).
    type OnDisk: Pod;

    /// Wrap a range as a typed handle (no I/O, no validation).
    fn from_range(range: BStackRange) -> Self;

    /// The underlying range this handle points at.
    fn range(&self) -> BStackRange;

    /// Recursively free this block's owned children given its `range`, **without**
    /// freeing the block itself — used when the block is `#[embed]`ded (its storage
    /// is part of the parent) and by `bstack_drop` before the self-dealloc. The
    /// generated impl overrides this; the default (a **childless** block) frees
    /// nothing. Exposed on the trait — rather than as a generated inherent method —
    /// so a generic parent can recurse into a type parameter. `#[doc(hidden)]`.
    #[doc(hidden)]
    fn __bstack_drop_children<A: BStackRaiiAllocator>(
        range: BStackRange,
        allocator: &A,
    ) -> io::Result<()> {
        let _ = (range, allocator);
        Ok(())
    }

    /// Read this block's `OnDisk` and return a deep-cloned copy for a
    /// [`ClonePlan`]: owned children cloned into the plan, shared children's
    /// refcounts bumped, embedded children folded in place — *without* allocating
    /// a block for `self`. The generated `#[bstack_block]` impl overrides this
    /// with the field-aware body; the default (used by hand-written impls of a
    /// **childless** block) copies the `OnDisk` verbatim. Exposed on the trait —
    /// rather than as a generated inherent method — so a generic parent can
    /// recurse into a type parameter's clone. `#[doc(hidden)]`: an impl detail.
    #[doc(hidden)]
    fn __bstack_clone_children_inplace<A: BStackRaiiAllocator>(
        &self,
        allocator: &A,
        _plan: &mut ClonePlan,
    ) -> io::Result<Self::OnDisk> {
        let mut buf = std::vec![0u8; core::mem::size_of::<Self::OnDisk>()];
        let r = unsafe { BStackRef::<Self>::from_range(self.range()) };
        Ok(*r.read_on_disk(allocator.stack(), &mut buf)?)
    }

    /// Deep-clone this block's subtree into a [`ClonePlan`]: allocate a fresh
    /// destination block, recurse into children via
    /// [`__bstack_clone_children_inplace`](Self::__bstack_clone_children_inplace),
    /// and stage the destination payload (writes are staged, committed by the
    /// caller). Overridden by the generated impl; the default suffices for a
    /// childless block. `#[doc(hidden)]`: an impl detail.
    #[doc(hidden)]
    fn __bstack_clone_into<A: BStackRaiiAllocator>(
        &self,
        allocator: &A,
        plan: &mut ClonePlan,
    ) -> io::Result<BStackRange> {
        let od = self.__bstack_clone_children_inplace(allocator, plan)?;
        let dst = plan.alloc_raw(allocator, core::mem::size_of::<Self::OnDisk>() as u64)?;
        plan.write(dst.start(), bytemuck::bytes_of(&od).to_vec());
        Ok(dst)
    }
}

/// The per-block field destructure behind `bstack_move!`: read every field, then
/// free only the parent *shell* (the children stay live on disk). Ownership is
/// transferred out — owned children as `BStackOwned`, strong as `BStackRc`, weak
/// as `Option<BStackWeak>`, refs as `BStackRef`, POD by value.
///
/// Generated on the block type `X` (a local type downstream, so it satisfies the
/// orphan rule) for **all** modes. It is the shared core used by both the owned
/// and the `Rc` `bstack_move!` paths in [`BStackMoveExpr`]; it does not touch
/// refcounts or the control block, so the caller must have already established
/// that the shell may be freed.
///
/// Takes the (bare, allocator-less) [`BStackOwned`] handle plus an explicit
/// allocator, since neither the owned handle nor the block type carries one.
pub trait BStackMove: BStackBlock {
    /// The tuple of field handles produced, in field-declaration order.
    type Fields<'a, A: BStackRaiiAllocator>;
    fn bstack_move<'a, A: BStackRaiiAllocator>(
        owned: BStackOwned<Self>,
        allocator: &'a A,
    ) -> io::Result<Self::Fields<'a, A>>;
}

/// The `bstack_move!` entry point, dispatched on the wrapper handle type.
///
/// * `BStackOwned<X>` — infallible; `Output = io::Result<X::Fields>`.
/// * `BStackRc<X>` — a `try_unwrap`: `Output = io::Result<Result<X::Fields, Self>>`,
///   succeeding only when this handle is the **sole strong owner** (else the
///   handle is returned in `Err`).
///
/// The macro emits `BStackMoveExpr::bstack_move(expr)` and lets inference select
/// the impl from the argument's type.
pub trait BStackMoveExpr {
    type Output;
    fn bstack_move(self) -> Self::Output;
}

/// Implemented by refcounted blocks (`#[bstack_block(rc)]` and
/// `#[bstack_block(rc, weak)]`), i.e. any block that can be the target of a
/// `#[bstack_strong]` field.
///
/// It abstracts "drop one strong reference to a child of this type" so a
/// parent's generated teardown does not need to know whether the child is a
/// plain `(rc)` block (inline refcount, [`crate::StrongRef`]) or an
/// `(rc, weak)` block (control block, [`crate::StrongWeakRef`]). The child's own
/// `#[bstack_block]` expansion picks the right implementation.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a reference-counted block (`#[bstack_block(rc)]` / `(rc, weak)`)",
    label = "not a shared block",
    note = "`#[bstack_strong]` fields (and generic parameters used as them) require an \
            `#[bstack_block(rc)]` or `#[bstack_block(rc, weak)]` type."
)]
pub trait BStackShared: BStackBlock {
    /// Drop one strong reference to a block of this type located at `data`,
    /// freeing it (and, for `(rc, weak)`, releasing the control block) when the
    /// strong count reaches zero.
    fn drop_strong_ref<A: BStackRaiiAllocator>(
        data: BStackRef<Self>,
        allocator: &A,
    ) -> io::Result<()>;

    /// Resolve the raw parts of a strong handle to a child of this type at
    /// `data`: the data ref, plus the control-block range for `(rc, weak)`
    /// blocks (`None` for plain `(rc)`). Used by `bstack_move!` to rebuild a
    /// `BStackRc` for a `#[bstack_strong]` field.
    fn strong_parts<A: BStackRaiiAllocator>(
        data: BStackRef<Self>,
        allocator: &A,
    ) -> io::Result<(BStackRef<Self>, Option<BStackRange>)>;
}

/// Implemented only for blocks declared `#[bstack_block(rc, weak)]`.
///
/// Its presence is what lets [`crate::BStackRc`] expose `downgrade` and
/// [`crate::BStackWeak`] exist for the type. `Control` is the generated
/// `XOnDiskRef` control-block payload holding the `strong`/`weak` counters.
/// Plain `#[bstack_block(rc)]` blocks do not implement it, so weak references to
/// them are a compile error rather than a runtime hazard.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a weak-observable block (`#[bstack_block(rc, weak)]`)",
    label = "not a weakable block",
    note = "`#[bstack_weak]` fields (and generic parameters used as them) require an \
            `#[bstack_block(rc, weak)]` type; a plain `#[bstack_block(rc)]` is not weak-observable."
)]
pub trait BStackWeakable: BStackBlock {
    /// The on-disk control-block payload (the generated `XOnDiskRef`).
    type Control: Pod;
}
