//! Fallible clone for handles whose duplication touches disk.
//!
//! Two flavours, split by what the duplication needs:
//!
//! * [`TryClone`] — a same-type clone that needs **no allocator**. Implemented by
//!   [`crate::BStackRc`] / [`crate::BStackWeak`], whose clone only bumps an
//!   on-disk refcount (they carry their own allocator).
//! * [`TryCloneIn`] — a **deep** clone of a whole block, producing a fresh
//!   independent [`BStackOwned`] copy. A without-allocator block handle
//!   (`X(BStackRange)`) has no allocator to allocate the copy with, so the
//!   allocator is passed in. Generated by `#[bstack_block]` (mirror of the
//!   block's `__bstack_drop_children` teardown, run in reverse):
//!     - POD / `#[bstack_ref]` fields — byte-copied (a ref aliases the same
//!       borrowed target; see the borrow-rules TODO);
//!     - `#[bstack_owned]` — recursively deep-cloned into a fresh child;
//!     - `#[bstack_strong]` / `#[bstack_weak]` — the shared target's refcount is
//!       bumped (the clone stays shared, not copied).
//!
//! # Atomicity model
//!
//! A deep clone mixes two workloads with different atomicity domains:
//! **allocations** (which extend the stack and cannot be part of an atomic
//! in-place batch) and **writes** (in-place payload writes, which can). So
//! [`TryCloneIn`] is built as two hard-separated phases via [`ClonePlan`]:
//!
//! 1. **Plan + allocate.** Recurse the block graph, allocating every new block
//!    up front (each fallible) and recording the payload bytes to write — but
//!    committing *no* write yet. A mid-descent allocation failure rolls back with
//!    zero payload written, so there is no partially-fixed-up state to repair.
//! 2. **Commit.** Once every allocation has succeeded, apply the refcount bumps
//!    and flush every payload write as one crash-atomic [`BStack::set_batched`]
//!    batch (the new blocks are distinct ranges, so the writes never overlap).
//!
//! A crash *between* the phases leaks the allocated-but-uncommitted blocks (a
//! recoverable leak, since the clone result is not yet reachable from any
//! persistent root) but never a torn write.

use std::io;

use bstack::{BStackGenOp, BStackOwnedSliceAllocator, BStackRange};

use crate::block::{BStackBlock, BStackShared};
use crate::layout;
use crate::owned::BStackOwned;
use crate::reference::BStackRef;
use crate::teardown::{BStackDrop, dealloc_range};
use crate::vec::{BYTEVEC_HEADER, VecDesc};
use crate::wal::{
    BStackWalAnchor, WalEntry, WalLog, WalStatus, finish_at_locked, persist_at, wal_lock_for,
    wal_set_idle,
};

/// Duplicate `self`, performing any fallible I/O the duplication requires,
/// **without** needing an allocator.
///
/// This is how a **shared** block is cloned: [`crate::BStackRc`] and
/// [`crate::BStackWeak`] implement it by bumping an on-disk refcount and handing
/// back another handle to the *same* block — exactly like `Rc::clone` /
/// `shared_ptr` copy in Rust / C++. A shared block is deliberately **not**
/// deep-copied into an independent [`BStackOwned`] via [`TryCloneIn`]; sharing,
/// not copying, is its defining semantics.
///
/// This matters most for the **weak** case: there is no coherent deep copy of a
/// weak reference. A weak reference observes a live object's *control block*; a
/// "deep copy" would have to either point at the same live object (in which case
/// it is just another weak handle — a count bump, which is what this does) or at
/// some fresh object (in which case it observes nothing the original observed, so
/// it is not a copy at all). So `BStackWeak::try_clone` bumps the weak count and
/// returns another weak handle to the same control block — the only sound
/// meaning a weak clone can have.
pub trait TryClone: Sized {
    fn try_clone(&self) -> io::Result<Self>;
}

/// Deep-clone a whole block into a fresh, independent [`BStackOwned`] copy,
/// allocating the copy with the supplied allocator.
///
/// Generated by `#[bstack_block]` for **plain** (uniquely-owned) blocks only.
/// Owned children are deep copied; shared (`#[bstack_strong]` / `#[bstack_weak]`)
/// children stay shared (their refcount is bumped); POD and `#[bstack_ref]`
/// fields are byte-copied.
///
/// A **shared** (`rc` / `rc, weak`) block does *not* implement this — its clone
/// is a handle duplication (a refcount bump) via [`TryClone`], not a deep copy,
/// so `try_clone_in` on such a block is a compile error that points you at
/// `BStackRc::try_clone` / `BStackWeak::try_clone` instead. See [`TryClone`] for
/// why (in particular, why a weak reference can only ever be cloned as another
/// weak reference).
pub trait TryCloneIn: BStackDrop + Sized {
    fn try_clone_in<A: BStackWalAnchor>(&self, allocator: &A) -> io::Result<BStackOwned<Self>>;
}

/// Accumulates a deep clone's allocations, payload writes, and refcount bumps so
/// the writes commit as one atomic batch after every allocation has succeeded.
///
/// See the [module docs](self#atomicity-model) for the two-phase model. Built up
/// by the generated `__bstack_clone_into` methods during the recursive descent,
/// then either [`commit`](Self::commit)ted or [`rollback`](Self::rollback)ed.
pub struct ClonePlan {
    /// New blocks allocated during planning; freed in reverse on rollback.
    allocated: Vec<BStackRange>,
    /// Pending in-place payload writes `(offset, bytes)`, flushed as one batch.
    writes: Vec<(u64, Vec<u8>)>,
    /// Absolute offsets of `u64` counters to increment by 1 at commit (the
    /// strong/weak counts a `#[bstack_strong]` / `#[bstack_weak]` clone acquires).
    bumps: Vec<u64>,
}

impl Default for ClonePlan {
    fn default() -> Self {
        Self::new()
    }
}

impl ClonePlan {
    /// A fresh, empty plan.
    pub fn new() -> Self {
        ClonePlan {
            allocated: Vec::new(),
            writes: Vec::new(),
            bumps: Vec::new(),
        }
    }

    /// Allocate a `size`-byte block **without writing anything**, recording it
    /// for rollback. The caller supplies the block's bytes later via
    /// [`write`](Self::write). The allocator's owned-slice handle is not RAII, so
    /// letting it drop here does not free the block.
    pub fn alloc_raw<A: BStackWalAnchor>(
        &mut self,
        allocator: &A,
        size: u64,
    ) -> io::Result<BStackRange> {
        let slice = allocator.alloc(size)?;
        let range = slice.as_range();
        self.allocated.push(range);
        Ok(range)
    }

    /// Record a pending in-place write of `bytes` at absolute `offset`.
    pub fn write(&mut self, offset: u64, bytes: Vec<u8>) {
        self.writes.push((offset, bytes));
    }

    /// Register an already-allocated range for rollback — for allocations made
    /// outside [`alloc_raw`](Self::alloc_raw).
    pub fn track_alloc(&mut self, range: BStackRange) {
        self.allocated.push(range);
    }

    /// Stage a fresh `BStackByteVec` data block holding `data` into the plan:
    /// allocate the block (`[len | cap | data]`, `16`-byte header) via
    /// [`alloc_raw`](Self::alloc_raw), stage its full on-disk image into the
    /// commit batch, and return its descriptor. This folds a cloned vector's data
    /// block into the plan's single atomic commit — the block is allocated through
    /// our machinery and its bytes ride the same `inplace_gen` as everything else,
    /// instead of the vector runtime writing it eagerly. `cap == len` (a fresh
    /// clone carries no spare capacity, matching `BStackByteVec::from_slice`).
    pub fn stage_bytevec<A: BStackWalAnchor>(
        &mut self,
        allocator: &A,
        data: &[u8],
    ) -> io::Result<VecDesc> {
        let len = data.len() as u64;
        let size = BYTEVEC_HEADER + len;
        let range = self.alloc_raw(allocator, size)?;
        // cap == len: a fresh clone carries no spare capacity.
        self.write(range.start(), crate::vec::bytevec_image(len, len, data));
        Ok(VecDesc {
            data_off: range.start(),
            data_size: size,
        })
    }

    /// Record that the strong count of a shared child at `data` must be bumped by
    /// one — the strong reference this clone's `#[bstack_strong]` field acquires.
    pub fn bump_strong<T: BStackShared, A: BStackWalAnchor>(
        &mut self,
        data: BStackRef<T>,
        allocator: &A,
    ) -> io::Result<()> {
        let (data_ref, ctrl) = T::strong_parts(data, allocator)?;
        let off = match ctrl {
            None => data_ref.into_range().start() + layout::RC_REFCOUNT_OFFSET,
            Some(c) => c.start() + layout::CTRL_STRONG_OFFSET,
        };
        self.bumps.push(off);
        Ok(())
    }

    /// Record that the weak count of the control block at `ctrl_off` must be
    /// bumped by one — the weak reference this clone's `#[bstack_weak]` field
    /// acquires.
    pub fn bump_weak(&mut self, ctrl_off: u64) {
        self.bumps.push(ctrl_off + layout::CTRL_WEAK_OFFSET);
    }

    /// Free everything allocated so far, in reverse order. The error path, taken
    /// when planning fails before [`commit`](Self::commit).
    pub fn rollback<A: BStackWalAnchor>(self, allocator: &A) {
        Self::free_all(self.allocated, allocator);
    }

    /// Commit the whole plan as **one** crash-atomic unit: every refcount bump
    /// (as an atomic read-modify-write) and every staged payload / vec-data write,
    /// via a single [`BStack::inplace_gen`]. Either all of it lands or none of it
    /// does. On failure (I/O, or a refcount overflow) nothing is committed and the
    /// plan's allocations are freed.
    ///
    /// Bumps are de-duplicated to distinct counters (a shared child referenced N
    /// times in the clone is one counter `+N`), then applied as **all reads, then
    /// all writes**: because the counters are distinct, no read depends on another
    /// bump's pending write, so an overflow can be detected after the reads —
    /// before any write is emitted — and abort with nothing committed.
    ///
    /// **Crash reclamation is automatic**: when the allocator names a WAL anchor
    /// ([`BStackWalAnchor::wal_anchor`] returns `Some`), the plan's fresh
    /// allocations are logged `Pending` before the commit and reclaimed by
    /// [`crate::wal::finish`] on the next open if the process dies mid-commit; the
    /// transaction is flipped `Complete` *inside* the commit batch, so "clone
    /// committed" and "WAL Complete" are the same atomic event. An allocator that
    /// returns `None` behaves exactly as before (mid-commit crash ⇒ orphan leak).
    pub fn commit<A: BStackWalAnchor>(self, allocator: &A) -> io::Result<()> {
        let anchor = allocator.wal_anchor();
        self.commit_inner(allocator, anchor)
    }

    fn commit_inner<A: BStackWalAnchor>(
        self,
        allocator: &A,
        anchor: Option<u64>,
    ) -> io::Result<()> {
        let ClonePlan {
            allocated,
            writes,
            mut bumps,
        } = self;
        let stack = allocator.stack();

        // Serialize the WAL transaction against other WAL-backed ops on this file
        // (the persistent block + anchor are single-writer). Held for the whole
        // commit; `None` when this clone isn't WAL-backed. `_wal_lock` must outlive
        // `_wal_guard`, so it is bound first.
        let _wal_lock = anchor.map(|_| wal_lock_for(allocator));
        let _wal_guard = _wal_lock
            .as_ref()
            .map(|l| l.lock().unwrap_or_else(|e| e.into_inner()));

        // With a WAL anchor, protect this clone's fresh allocations: log them
        // `Pending` before the commit, so a crash mid-commit is reclaimed by
        // `finish` on the next open. The transaction is flipped `Complete` *inside*
        // the commit batch below, so "clone committed" and "WAL Complete" are the
        // same atomic event.
        let wal: Option<(u64, BStackRange)> = match anchor {
            Some(anchor) if !allocated.is_empty() => {
                let mut log = WalLog::with_capacity(allocated.len());
                for &r in &allocated {
                    log.append(WalEntry::alloc(WalStatus::Pending, r));
                }
                match persist_at(allocator, anchor, &log, WalStatus::Pending) {
                    Ok(range) => Some((anchor, range)),
                    Err(e) => {
                        // Couldn't stage the WAL — fall back to an immediate rollback.
                        Self::free_all(allocated, allocator);
                        return Err(e);
                    }
                }
            }
            _ => None,
        };

        // De-duplicate bump offsets into distinct `(counter, delta)`.
        bumps.sort_unstable();
        let mut counters: Vec<(u64, u64)> = Vec::new();
        for off in bumps {
            match counters.last_mut() {
                Some(last) if last.0 == off => last.1 += 1,
                _ => counters.push((off, 1)),
            }
        }

        // Buffers that must outlive the whole `inplace_gen` call (bstack's
        // documented generator pattern): the read-back counter values and the
        // computed new values. `writes` is borrowed for its `Write` data.
        let n = counters.len();
        let mut readbufs: Vec<[u8; 8]> = vec![[0u8; 8]; n];
        let mut newbufs: Vec<[u8; 8]> = vec![[0u8; 8]; n];
        let mut overflow = false;

        // The WAL commit marker (`WalHeader.txn_status`, the byte after the u64
        // magic). Written last, so it lands in the same atomic batch as the clone.
        let flip = [WalStatus::Complete as u8];
        let flip_off = wal.map(|(_, r)| r.start() + 8);
        let mut flipped = flip_off.is_none();

        let mut read_i = 0usize;
        let mut computed = false;
        let mut cwrite_i = 0usize;
        let mut write_i = 0usize;

        let result = stack.inplace_gen(|_feedback| {
            // Phase 1 — read every distinct counter.
            if read_i < n {
                let i = read_i;
                read_i += 1;
                // SAFETY: `readbufs` outlives this `inplace_gen` call and each
                // read buffer is used by exactly one in-flight `Read` op.
                let buf: &mut [u8] =
                    unsafe { core::mem::transmute::<&mut [u8], _>(&mut readbufs[i][..]) };
                return Some(BStackGenOp::Read {
                    offset: counters[i].0,
                    buf,
                });
            }
            // Transition — compute new values + check overflow before any write.
            if !computed {
                computed = true;
                for i in 0..n {
                    let cur = u64::from_le_bytes(readbufs[i]);
                    match cur.checked_add(counters[i].1) {
                        Some(v) => newbufs[i] = v.to_le_bytes(),
                        None => overflow = true,
                    }
                }
                if overflow {
                    // No `Write` emitted yet → ending now commits nothing.
                    return None;
                }
            }
            // Phase 2a — write the incremented counters.
            if cwrite_i < n {
                let i = cwrite_i;
                cwrite_i += 1;
                // SAFETY: `newbufs` outlives this call; each slot is written once
                // above and only read here.
                let data: &[u8] = unsafe { core::mem::transmute::<&[u8], _>(&newbufs[i][..]) };
                return Some(BStackGenOp::Write {
                    offset: counters[i].0,
                    data,
                });
            }
            // Phase 2b — write every staged payload / vec-data block.
            if write_i < writes.len() {
                let i = write_i;
                write_i += 1;
                let (off, ref bytes) = writes[i];
                // SAFETY: `writes` outlives this call; each entry is read once.
                let data: &[u8] = unsafe { core::mem::transmute::<&[u8], _>(bytes.as_slice()) };
                return Some(BStackGenOp::Write { offset: off, data });
            }
            // Phase 2c — flip the WAL transaction to `Complete`, last, so it commits
            // atomically with the clone's writes (a no-op when there is no WAL).
            if !flipped {
                flipped = true;
                // SAFETY: `flip` outlives this call and is only read here.
                let data: &[u8] = unsafe { core::mem::transmute::<&[u8], _>(&flip[..]) };
                return Some(BStackGenOp::Write {
                    offset: flip_off.unwrap(),
                    data,
                });
            }
            None
        });

        match result {
            Ok(()) if overflow => {
                Self::reclaim(allocated, wal, allocator);
                Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "refcount overflow while committing clone",
                ))
            }
            Ok(()) => {
                // Committed — the WAL was flipped `Complete` in the same batch. A
                // clone logs only `Alloc`s, which a committed txn keeps, so there is
                // nothing to roll forward: just mark the persistent block idle for
                // reuse (a crash before this is harmlessly finished on the next open,
                // freeing nothing). The block itself is never freed.
                if let Some((_anchor, wal_range)) = wal {
                    let _ = wal_set_idle(allocator, wal_range.start());
                }
                Ok(())
            }
            // `inplace_gen` is atomic: on error nothing committed. Reclaim the
            // plan's allocations (via the WAL if present, else directly).
            Err(e) => {
                Self::reclaim(allocated, wal, allocator);
                Err(e)
            }
        }
    }

    /// Reclaim a failed commit's allocations. With a WAL, `finish_at_locked`
    /// abandons the still-`Pending` transaction — freeing the logged alloc orphans
    /// and marking the persistent block idle — matching exactly what `finish` would
    /// do after a real crash; without one, free them directly. The WAL lock is
    /// already held by the caller (`commit_inner`), so the *locked* variant is used.
    fn reclaim<A: BStackWalAnchor>(
        allocated: Vec<BStackRange>,
        wal: Option<(u64, BStackRange)>,
        allocator: &A,
    ) {
        match wal {
            Some((anchor, _)) => {
                let _ = finish_at_locked(allocator, anchor);
            }
            None => Self::free_all(allocated, allocator),
        }
    }

    fn free_all<A: BStackWalAnchor>(allocated: Vec<BStackRange>, allocator: &A) {
        for r in allocated.into_iter().rev() {
            // SAFETY: each range was returned by our own `alloc_raw` and never
            // handed to another owner, so freeing it here is sound.
            let _ = unsafe { dealloc_range(allocator, r) };
        }
    }
}
