//! Fallible clone for handles whose duplication touches disk.
//!
//! Two flavours, split by what the duplication needs:
//!
//! * [`TryClone`] — a same-type clone that needs **no allocator**. Implemented by
//!   [`crate::BStackRc`] / [`crate::BStackWeak`], whose clone only bumps an
//!   on-disk refcount (they carry their own allocator).
//! * [`TryCloneIn`] — a **deep** clone of a whole block, producing a fresh
//!   independent [`BStackOwned`] copy. A without-allocator block handle
//!   (`X(BStackRange)`) has no allocator to allocate the copy with, so the
//!   allocator is passed in. Generated by `#[bstack_block]` (mirror of the
//!   block's `__bstack_drop_children` teardown, run in reverse):
//!     - POD / `#[bstack_ref]` fields — byte-copied (a ref aliases the same
//!       borrowed target; see the borrow-rules TODO);
//!     - `#[bstack_owned]` — recursively deep-cloned into a fresh child;
//!     - `#[bstack_strong]` / `#[bstack_weak]` — the shared target's refcount is
//!       bumped (the clone stays shared, not copied).
//!
//! # Atomicity model
//!
//! A deep clone mixes two workloads with different atomicity domains:
//! **allocations** (which extend the stack and cannot be part of an atomic
//! in-place batch) and **writes** (in-place payload writes, which can). So
//! [`TryCloneIn`] is built as two hard-separated phases via [`ClonePlan`]:
//!
//! 1. **Plan + allocate.** Recurse the block graph, allocating every new block
//!    up front (each fallible) and recording the payload bytes to write — but
//!    committing *no* write yet. A mid-descent allocation failure rolls back with
//!    zero payload written, so there is no partially-fixed-up state to repair.
//! 2. **Commit.** Once every allocation has succeeded, apply the refcount bumps
//!    and flush every payload write as one crash-atomic [`BStack::set_batched`]
//!    batch (the new blocks are distinct ranges, so the writes never overlap).
//!
//! A crash *between* the phases would leak the allocated-but-uncommitted blocks,
//! never a torn write (the clone result is not yet reachable from any persistent
//! root). When the allocator names a WAL anchor ([`BStackRaiiAllocator::wal_anchor`]
//! returns `Some`), phase 1 is additionally **intention-first**: each allocation is
//! logged `Pending` to the persistent WAL block the instant it is made
//! ([`ClonePlan::alloc_raw`]), so a crash mid-descent is *reclaimed* by
//! [`crate::wal::finish`] on the next open — down to a one-block window (the block
//! allocated but not yet logged). The phase-2 commit flips that transaction
//! `Complete` inside the same atomic batch, so "clone committed" and "WAL Complete"
//! are one event. Because the WAL block is a single-writer-per-file singleton, the
//! plan holds the file's WAL lock for the whole descent; concurrent deep clones on
//! the *same* file therefore serialize (they still run fully concurrently across
//! different files). An allocator that names no anchor keeps the plain two-phase
//! behaviour (mid-descent crash ⇒ orphan leak).

use std::io;
use std::sync::{Arc, Mutex, MutexGuard};

use bstack::{BStackGenOp, BStackRange};

use crate::BStackRaiiAllocator;
use crate::block::BStackShared;
use crate::layout;
use crate::owned::BStackOwned;
use crate::reference::BStackRef;
use crate::teardown::{BStackDrop, dealloc_range};
use crate::vec::{BYTEVEC_HEADER, VecDesc};
use crate::wal::{
    WalEntry, WalLog, WalStatus, finish_at_locked, persist_at, wal_append_alloc, wal_capacity_of,
    wal_lock_for, wal_set_idle,
};

/// Duplicate `self`, performing any fallible I/O the duplication requires,
/// **without** needing an allocator.
///
/// This is how a **shared** block is cloned: [`crate::BStackRc`] and
/// [`crate::BStackWeak`] implement it by bumping an on-disk refcount and handing
/// back another handle to the *same* block — exactly like `Rc::clone` /
/// `shared_ptr` copy in Rust / C++. A shared block is deliberately **not**
/// deep-copied into an independent [`BStackOwned`] via [`TryCloneIn`]; sharing,
/// not copying, is its defining semantics.
///
/// This matters most for the **weak** case: there is no coherent deep copy of a
/// weak reference. A weak reference observes a live object's *control block*; a
/// "deep copy" would have to either point at the same live object (in which case
/// it is just another weak handle — a count bump, which is what this does) or at
/// some fresh object (in which case it observes nothing the original observed, so
/// it is not a copy at all). So `BStackWeak::try_clone` bumps the weak count and
/// returns another weak handle to the same control block — the only sound
/// meaning a weak clone can have.
pub trait TryClone: Sized {
    fn try_clone(&self) -> io::Result<Self>;
}

/// Deep-clone a whole block into a fresh, independent [`BStackOwned`] copy,
/// allocating the copy with the supplied allocator.
///
/// Generated by `#[bstack_block]` for **plain** (uniquely-owned) blocks only.
/// Owned children are deep copied; shared (`#[bstack_strong]` / `#[bstack_weak]`)
/// children stay shared (their refcount is bumped); POD and `#[bstack_ref]`
/// fields are byte-copied.
///
/// A **shared** (`rc` / `rc, weak`) block does *not* implement this — its clone
/// is a handle duplication (a refcount bump) via [`TryClone`], not a deep copy,
/// so `try_clone_in` on such a block is a compile error that points you at
/// `BStackRc::try_clone` / `BStackWeak::try_clone` instead. See [`TryClone`] for
/// why (in particular, why a weak reference can only ever be cloned as another
/// weak reference).
pub trait TryCloneIn: BStackDrop + Sized {
    fn try_clone_in<A: BStackRaiiAllocator>(&self, allocator: &A) -> io::Result<BStackOwned<Self>>;
}

/// Accumulates a deep clone's allocations, payload writes, and refcount bumps so
/// the writes commit as one atomic batch after every allocation has succeeded.
///
/// See the [module docs](self#atomicity-model) for the two-phase model. Built up
/// by the generated `__bstack_clone_into` methods during the recursive descent,
/// then either [`commit`](Self::commit)ted or [`rollback`](Self::rollback)ed.
pub struct ClonePlan {
    /// New blocks allocated during planning; freed in reverse on rollback.
    allocated: Vec<BStackRange>,
    /// Pending in-place payload writes `(offset, bytes)`, flushed as one batch.
    writes: Vec<(u64, Vec<u8>)>,
    /// Absolute offsets of `u64` counters to increment by 1 at commit (the
    /// strong/weak counts a `#[bstack_strong]` / `#[bstack_weak]` clone acquires).
    bumps: Vec<u64>,
    /// The intention-first WAL transaction, lazily begun on the first allocation
    /// through [`alloc_raw`](Self::alloc_raw) when the allocator names a WAL anchor
    /// (`None` until then, or forever if the allocator opts out of reclamation). Its
    /// [`HeldLock`] pins the file's WAL lock for the whole descent + commit; the
    /// invariant is that its logged `Pending` `Alloc` entries are *exactly*
    /// [`allocated`](Self::allocated), so [`finish`](crate::wal::finish) reclaims
    /// precisely those on abandon.
    wal: Option<CloneWal>,
}

/// The in-flight intention-first WAL transaction of a [`ClonePlan`]: the file's
/// WAL lock held for the descent, plus the persistent block's offset, entry-slot
/// capacity, and how many entries have been published so far.
struct CloneWal {
    /// Holds the file's WAL lock until the plan is committed / rolled back.
    _held: HeldLock,
    /// Offset of the persistent WAL block (moves if a grow reallocates it).
    block_off: u64,
    /// Entry slots the block currently has.
    capacity: u64,
    /// Entries published so far (== `ClonePlan::allocated.len()`).
    logged: u64,
}

/// The file's WAL [`Mutex`] held across a whole clone transaction. It owns the
/// `Arc` so the lifetime-extended guard can never outlive the mutex it borrows;
/// `Drop` releases the guard *before* the `Arc` is dropped.
struct HeldLock {
    /// `Some` while held; taken in `Drop` so the guard releases before `_arc`.
    guard: Option<MutexGuard<'static, ()>>,
    /// Keeps the mutex alive for as long as `guard` borrows it.
    _arc: Arc<Mutex<()>>,
}

impl HeldLock {
    fn acquire(arc: Arc<Mutex<()>>) -> Self {
        let guard = arc.lock().unwrap_or_else(|e| e.into_inner());
        // SAFETY: the guard borrows the `Mutex` owned by `arc`, which this struct
        // keeps alive; `Drop` releases the guard before `arc` is dropped, so the
        // borrow never dangles. The transmute only extends the guard's lifetime to
        // `'static` to store it alongside its owning `Arc`.
        let guard: MutexGuard<'static, ()> = unsafe { core::mem::transmute(guard) };
        HeldLock {
            guard: Some(guard),
            _arc: arc,
        }
    }
}

impl Drop for HeldLock {
    fn drop(&mut self) {
        // Release the guard before `_arc` drops (which would free the `Mutex`).
        self.guard = None;
    }
}

impl Default for ClonePlan {
    fn default() -> Self {
        Self::new()
    }
}

impl ClonePlan {
    /// A fresh, empty plan.
    pub fn new() -> Self {
        ClonePlan {
            allocated: Vec::new(),
            writes: Vec::new(),
            bumps: Vec::new(),
            wal: None,
        }
    }

    /// Allocate a `size`-byte block **without writing anything**, recording it
    /// for rollback. The caller supplies the block's bytes later via
    /// [`write`](Self::write). The allocator's owned-slice handle is not RAII, so
    /// letting it drop here does not free the block.
    ///
    /// This is the single funnel for every deep-clone allocation (plain child
    /// blocks and, via [`stage_bytevec`](Self::stage_bytevec), vec data blocks), so
    /// it is also where the **intention-first WAL** hooks in: when the allocator
    /// names a WAL anchor, the freshly allocated block is logged `Pending` before
    /// this returns, so a crash mid-descent is reclaimed on the next open. The
    /// allocation and its log entry are kept in lockstep — if logging fails the
    /// block is freed again before returning the error — so the WAL's live entries
    /// always equal [`allocated`](Self::allocated).
    pub fn alloc_raw<A: BStackRaiiAllocator>(
        &mut self,
        allocator: &A,
        size: u64,
    ) -> io::Result<BStackRange> {
        let slice = allocator.alloc(size)?;
        let range = slice.as_range();
        if allocator.wal_anchor().is_some()
            && let Err(e) = self.wal_log_alloc(allocator, range)
        {
            // Keep `allocated`/logged in sync: undo this alloc, log nothing.
            let _ = allocator.dealloc(slice);
            return Err(e);
        }
        self.allocated.push(range);
        Ok(range)
    }

    /// Log a just-made allocation to the intention-first WAL, (lazily) beginning
    /// the transaction on the first call. Cheap append (one entry + a `count` bump)
    /// while the block has spare slots; a full re-[`persist_at`] — which grows the
    /// block — when it is full. `self.allocated` does **not** yet contain `range`
    /// (the caller pushes it only after this succeeds), so the grow path logs the
    /// whole of `allocated` *plus* `range`.
    fn wal_log_alloc<A: BStackRaiiAllocator>(
        &mut self,
        allocator: &A,
        range: BStackRange,
    ) -> io::Result<()> {
        match &mut self.wal {
            None => {
                // First allocation: take the file's WAL lock for the whole descent
                // and stage a `Pending` block holding this one entry.
                let held = HeldLock::acquire(wal_lock_for(allocator));
                let mut log = WalLog::with_capacity(1);
                log.append(WalEntry::alloc(WalStatus::Pending, range));
                let block = persist_at(allocator, &log, WalStatus::Pending)?;
                self.wal = Some(CloneWal {
                    _held: held,
                    block_off: block.start(),
                    capacity: wal_capacity_of(block),
                    logged: 1,
                });
                Ok(())
            }
            Some(w) if w.logged < w.capacity => {
                wal_append_alloc(allocator, w.block_off, w.logged, range)?;
                w.logged += 1;
                Ok(())
            }
            Some(w) => {
                // Block full: re-persist the whole log (all of `allocated` plus this
                // new entry), which grows the block to the next power of two.
                let mut log = WalLog::with_capacity(self.allocated.len() + 1);
                for &r in &self.allocated {
                    log.append(WalEntry::alloc(WalStatus::Pending, r));
                }
                log.append(WalEntry::alloc(WalStatus::Pending, range));
                let block = persist_at(allocator, &log, WalStatus::Pending)?;
                w.block_off = block.start();
                w.capacity = wal_capacity_of(block);
                w.logged = self.allocated.len() as u64 + 1;
                Ok(())
            }
        }
    }

    /// Record a pending in-place write of `bytes` at absolute `offset`.
    pub fn write(&mut self, offset: u64, bytes: Vec<u8>) {
        self.writes.push((offset, bytes));
    }

    /// Register an already-allocated range for rollback — for allocations made
    /// outside [`alloc_raw`](Self::alloc_raw).
    pub fn track_alloc(&mut self, range: BStackRange) {
        self.allocated.push(range);
    }

    /// Stage a fresh `BStackByteVec` data block holding `data` into the plan:
    /// allocate the block (`[len | cap | data]`, `16`-byte header) via
    /// [`alloc_raw`](Self::alloc_raw), stage its full on-disk image into the
    /// commit batch, and return its descriptor. This folds a cloned vector's data
    /// block into the plan's single atomic commit — the block is allocated through
    /// our machinery and its bytes ride the same `inplace_gen` as everything else,
    /// instead of the vector runtime writing it eagerly. `cap == len` (a fresh
    /// clone carries no spare capacity, matching `BStackByteVec::from_slice`).
    pub fn stage_bytevec<A: BStackRaiiAllocator>(
        &mut self,
        allocator: &A,
        data: &[u8],
    ) -> io::Result<VecDesc> {
        let len = data.len() as u64;
        let size = BYTEVEC_HEADER + len;
        let range = self.alloc_raw(allocator, size)?;
        // cap == len: a fresh clone carries no spare capacity.
        self.write(range.start(), crate::vec::bytevec_image(len, len, data));
        Ok(VecDesc {
            data_off: range.start(),
            data_size: size,
        })
    }

    /// Record that the strong count of a shared child at `data` must be bumped by
    /// one — the strong reference this clone's `#[bstack_strong]` field acquires.
    pub fn bump_strong<T: BStackShared, A: BStackRaiiAllocator>(
        &mut self,
        data: BStackRef<T>,
        allocator: &A,
    ) -> io::Result<()> {
        let (data_ref, ctrl) = T::strong_parts(data, allocator)?;
        let off = match ctrl {
            None => data_ref.into_range().start() + layout::RC_REFCOUNT_OFFSET,
            Some(c) => c.start() + layout::CTRL_STRONG_OFFSET,
        };
        self.bumps.push(off);
        Ok(())
    }

    /// Record that the weak count of the control block at `ctrl_off` must be
    /// bumped by one — the weak reference this clone's `#[bstack_weak]` field
    /// acquires.
    pub fn bump_weak(&mut self, ctrl_off: u64) {
        self.bumps.push(ctrl_off + layout::CTRL_WEAK_OFFSET);
    }

    /// Free everything allocated so far. The error path, taken when planning fails
    /// before [`commit`](Self::commit).
    ///
    /// With an intention-first WAL in flight, the fresh allocations are logged
    /// `Pending`, so this abandons that transaction via [`finish`](crate::wal::finish)
    /// (freeing exactly the logged allocs — which equal `allocated` — and marking the
    /// persistent block idle), the same path a real crash takes; the WAL lock is held
    /// by `self` and released as it drops. Without a WAL the ranges are freed directly.
    pub fn rollback<A: BStackRaiiAllocator>(self, allocator: &A) {
        if self.wal.is_some() {
            // Abandon the still-`Pending` transaction; `self` (and its held WAL lock)
            // drops at the end of this call, after the reclamation has run.
            let _ = finish_at_locked(allocator);
        } else {
            Self::free_all(self.allocated, allocator);
        }
    }

    /// Commit the whole plan as **one** crash-atomic unit: every refcount bump
    /// (as an atomic read-modify-write) and every staged payload / vec-data write,
    /// via a single [`BStack::inplace_gen`]. Either all of it lands or none of it
    /// does. On failure (I/O, or a refcount overflow) nothing is committed and the
    /// plan's allocations are freed.
    ///
    /// Bumps are de-duplicated to distinct counters (a shared child referenced N
    /// times in the clone is one counter `+N`), then applied as **all reads, then
    /// all writes**: because the counters are distinct, no read depends on another
    /// bump's pending write, so an overflow can be detected after the reads —
    /// before any write is emitted — and abort with nothing committed.
    ///
    /// **Crash reclamation is automatic**: when the allocator names a WAL anchor
    /// ([`BStackRaiiAllocator::wal_anchor`] returns `Some`), the plan's fresh
    /// allocations were already logged `Pending` *during the descent*
    /// ([`alloc_raw`](Self::alloc_raw)) and are reclaimed by [`crate::wal::finish`]
    /// on the next open if the process dies before the commit lands; here that
    /// transaction is flipped `Complete` *inside* the commit batch, so "clone
    /// committed" and "WAL Complete" are the same atomic event. An allocator that
    /// returns `None` behaves exactly as before (mid-commit crash ⇒ orphan leak).
    pub fn commit<A: BStackRaiiAllocator>(self, allocator: &A) -> io::Result<()> {
        let ClonePlan {
            allocated,
            writes,
            mut bumps,
            wal,
        } = self;
        let stack = allocator.stack();

        // The WAL transaction (if any) was staged `Pending` incrementally during the
        // descent and its file lock is held by `wal._held`; here we only flip it
        // `Complete` inside the commit batch. A clone with no allocations has no WAL
        // (and needs no lock — the bumps ride bstack's own per-op atomicity).

        // De-duplicate bump offsets into distinct `(counter, delta)`.
        bumps.sort_unstable();
        let mut counters: Vec<(u64, u64)> = Vec::new();
        for off in bumps {
            match counters.last_mut() {
                Some(last) if last.0 == off => last.1 += 1,
                _ => counters.push((off, 1)),
            }
        }

        // Buffers that must outlive the whole `inplace_gen` call (bstack's
        // documented generator pattern): the read-back counter values and the
        // computed new values. `writes` is borrowed for its `Write` data.
        let n = counters.len();
        let mut readbufs: Vec<[u8; 8]> = vec![[0u8; 8]; n];
        let mut newbufs: Vec<[u8; 8]> = vec![[0u8; 8]; n];
        let mut overflow = false;

        // The WAL commit marker (`WalHeader.txn_status`, the byte after the u64
        // magic). Written last, so it lands in the same atomic batch as the clone.
        let flip = [WalStatus::Complete as u8];
        let flip_off = wal.as_ref().map(|w| w.block_off + 8);
        let mut flipped = flip_off.is_none();

        let mut read_i = 0usize;
        let mut computed = false;
        let mut cwrite_i = 0usize;
        let mut write_i = 0usize;

        let result = stack.inplace_gen(|_feedback| {
            // Phase 1 — read every distinct counter.
            if read_i < n {
                let i = read_i;
                read_i += 1;
                // SAFETY: `readbufs` outlives this `inplace_gen` call and each
                // read buffer is used by exactly one in-flight `Read` op.
                let buf: &mut [u8] =
                    unsafe { core::mem::transmute::<&mut [u8], _>(&mut readbufs[i][..]) };
                return Some(BStackGenOp::Read {
                    offset: counters[i].0,
                    buf,
                });
            }
            // Transition — compute new values + check overflow before any write.
            if !computed {
                computed = true;
                for i in 0..n {
                    let cur = u64::from_le_bytes(readbufs[i]);
                    match cur.checked_add(counters[i].1) {
                        Some(v) => newbufs[i] = v.to_le_bytes(),
                        None => overflow = true,
                    }
                }
                if overflow {
                    // No `Write` emitted yet → ending now commits nothing.
                    return None;
                }
            }
            // Phase 2a — write the incremented counters.
            if cwrite_i < n {
                let i = cwrite_i;
                cwrite_i += 1;
                // SAFETY: `newbufs` outlives this call; each slot is written once
                // above and only read here.
                let data: &[u8] = unsafe { core::mem::transmute::<&[u8], _>(&newbufs[i][..]) };
                return Some(BStackGenOp::Write {
                    offset: counters[i].0,
                    data,
                });
            }
            // Phase 2b — write every staged payload / vec-data block.
            if write_i < writes.len() {
                let i = write_i;
                write_i += 1;
                let (off, ref bytes) = writes[i];
                // SAFETY: `writes` outlives this call; each entry is read once.
                let data: &[u8] = unsafe { core::mem::transmute::<&[u8], _>(bytes.as_slice()) };
                return Some(BStackGenOp::Write { offset: off, data });
            }
            // Phase 2c — flip the WAL transaction to `Complete`, last, so it commits
            // atomically with the clone's writes (a no-op when there is no WAL).
            if !flipped {
                flipped = true;
                // SAFETY: `flip` outlives this call and is only read here.
                let data: &[u8] = unsafe { core::mem::transmute::<&[u8], _>(&flip[..]) };
                return Some(BStackGenOp::Write {
                    offset: flip_off.unwrap(),
                    data,
                });
            }
            None
        });

        match result {
            Ok(()) if overflow => {
                Self::reclaim(&wal, allocated, allocator);
                Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "refcount overflow while committing clone",
                ))
            }
            Ok(()) => {
                // Committed — the WAL was flipped `Complete` in the same batch. A
                // clone logs only `Alloc`s, which a committed txn keeps, so there is
                // nothing to roll forward: just mark the persistent block idle for
                // reuse (a crash before this is harmlessly finished on the next open,
                // freeing nothing). The block itself is never freed.
                if let Some(w) = &wal {
                    let _ = wal_set_idle(allocator, w.block_off);
                }
                Ok(())
            }
            // `inplace_gen` is atomic: on error nothing committed. Reclaim the
            // plan's allocations (via the WAL if present, else directly).
            Err(e) => {
                Self::reclaim(&wal, allocated, allocator);
                Err(e)
            }
        }
        // `wal` (holding the file's WAL lock) drops here, after reclamation.
    }

    /// Reclaim a failed commit's allocations. With a WAL, `finish_at_locked`
    /// abandons the still-`Pending` transaction — freeing the logged alloc orphans
    /// (exactly `allocated`) and marking the persistent block idle — matching what
    /// `finish` does after a real crash; without one, free them directly. The WAL
    /// lock is held by the still-live `wal` in the caller, so the *locked* variant
    /// is used.
    fn reclaim<A: BStackRaiiAllocator>(
        wal: &Option<CloneWal>,
        allocated: Vec<BStackRange>,
        allocator: &A,
    ) {
        match wal {
            // A WAL transaction is in flight: abandon it via the allocator's own
            // anchor (same as a real crash's `finish`); it frees the logged allocs.
            Some(_) => {
                let _ = finish_at_locked(allocator);
            }
            None => Self::free_all(allocated, allocator),
        }
    }

    fn free_all<A: BStackRaiiAllocator>(allocated: Vec<BStackRange>, allocator: &A) {
        for r in allocated.into_iter().rev() {
            // SAFETY: each range was returned by our own `alloc_raw` and never
            // handed to another owner, so freeing it here is sound.
            let _ = unsafe { dealloc_range(allocator, r) };
        }
    }
}
