//! Fallible clone for handles whose duplication touches disk.
//!
//! Two flavours, split by what the duplication needs:
//!
//! * [`TryClone`] — a same-type clone that needs **no allocator**. Implemented by
//!   [`crate::BStackRc`] / [`crate::BStackWeak`], whose clone only bumps an
//!   on-disk refcount (they carry their own allocator).
//! * [`TryCloneIn`] — a **deep** clone of a whole block, producing a fresh
//!   independent [`BStackOwned`] copy. A without-allocator block handle
//!   (`X(BStackRange)`) has no allocator to allocate the copy with, so the
//!   allocator is passed in. Generated by `#[bstack_block]` (mirror of the
//!   block's `__bstack_drop_children` teardown, run in reverse):
//!     - POD / `#[bstack_ref]` fields — byte-copied (a ref aliases the same
//!       borrowed target; see the borrow-rules TODO);
//!     - `#[bstack_owned]` — recursively deep-cloned into a fresh child;
//!     - `#[bstack_strong]` / `#[bstack_weak]` — the shared target's refcount is
//!       bumped (the clone stays shared, not copied).
//!
//! # Atomicity model
//!
//! A deep clone mixes two workloads with different atomicity domains:
//! **allocations** (which extend the stack and cannot be part of an atomic
//! in-place batch) and **writes** (in-place payload writes, which can). So
//! [`TryCloneIn`] is built as two hard-separated phases via [`ClonePlan`]:
//!
//! 1. **Plan + allocate.** Recurse the block graph, allocating every new block
//!    up front (each fallible) and recording the payload bytes to write — but
//!    committing *no* write yet. A mid-descent allocation failure rolls back with
//!    zero payload written, so there is no partially-fixed-up state to repair.
//! 2. **Commit.** Once every allocation has succeeded, apply the refcount bumps
//!    and flush every payload write as one crash-atomic [`BStack::set_batched`]
//!    batch (the new blocks are distinct ranges, so the writes never overlap).
//!
//! A crash *between* the phases leaks the allocated-but-uncommitted blocks (a
//! recoverable leak, since the clone result is not yet reachable from any
//! persistent root) but never a torn write.

use std::io;

use bstack::{BStackOwnedSliceAllocator, BStackRange};

use crate::block::BStackShared;
use crate::layout;
use crate::owned::BStackOwned;
use crate::reference::BStackRef;
use crate::refcount;
use crate::teardown::{BStackDrop, dealloc_range};

/// Duplicate `self`, performing any fallible I/O the duplication requires,
/// **without** needing an allocator.
///
/// This is how a **shared** block is cloned: [`crate::BStackRc`] and
/// [`crate::BStackWeak`] implement it by bumping an on-disk refcount and handing
/// back another handle to the *same* block — exactly like `Rc::clone` /
/// `shared_ptr` copy in Rust / C++. A shared block is deliberately **not**
/// deep-copied into an independent [`BStackOwned`] via [`TryCloneIn`]; sharing,
/// not copying, is its defining semantics.
///
/// This matters most for the **weak** case: there is no coherent deep copy of a
/// weak reference. A weak reference observes a live object's *control block*; a
/// "deep copy" would have to either point at the same live object (in which case
/// it is just another weak handle — a count bump, which is what this does) or at
/// some fresh object (in which case it observes nothing the original observed, so
/// it is not a copy at all). So `BStackWeak::try_clone` bumps the weak count and
/// returns another weak handle to the same control block — the only sound
/// meaning a weak clone can have.
pub trait TryClone: Sized {
    fn try_clone(&self) -> io::Result<Self>;
}

/// Deep-clone a whole block into a fresh, independent [`BStackOwned`] copy,
/// allocating the copy with the supplied allocator.
///
/// Generated by `#[bstack_block]` for **plain** (uniquely-owned) blocks only.
/// Owned children are deep copied; shared (`#[bstack_strong]` / `#[bstack_weak]`)
/// children stay shared (their refcount is bumped); POD and `#[bstack_ref]`
/// fields are byte-copied.
///
/// A **shared** (`rc` / `rc, weak`) block does *not* implement this — its clone
/// is a handle duplication (a refcount bump) via [`TryClone`], not a deep copy,
/// so `try_clone_in` on such a block is a compile error that points you at
/// `BStackRc::try_clone` / `BStackWeak::try_clone` instead. See [`TryClone`] for
/// why (in particular, why a weak reference can only ever be cloned as another
/// weak reference).
pub trait TryCloneIn: BStackDrop + Sized {
    fn try_clone_in<A: BStackOwnedSliceAllocator>(
        &self,
        allocator: &A,
    ) -> io::Result<BStackOwned<Self>>;
}

/// Accumulates a deep clone's allocations, payload writes, and refcount bumps so
/// the writes commit as one atomic batch after every allocation has succeeded.
///
/// See the [module docs](self#atomicity-model) for the two-phase model. Built up
/// by the generated `__bstack_clone_into` methods during the recursive descent,
/// then either [`commit`](Self::commit)ted or [`rollback`](Self::rollback)ed.
pub struct ClonePlan {
    /// New blocks allocated during planning; freed in reverse on rollback.
    allocated: Vec<BStackRange>,
    /// Pending in-place payload writes `(offset, bytes)`, flushed as one batch.
    writes: Vec<(u64, Vec<u8>)>,
    /// Absolute offsets of `u64` counters to increment by 1 at commit (the
    /// strong/weak counts a `#[bstack_strong]` / `#[bstack_weak]` clone acquires).
    bumps: Vec<u64>,
}

impl Default for ClonePlan {
    fn default() -> Self {
        Self::new()
    }
}

impl ClonePlan {
    /// A fresh, empty plan.
    pub fn new() -> Self {
        ClonePlan {
            allocated: Vec::new(),
            writes: Vec::new(),
            bumps: Vec::new(),
        }
    }

    /// Allocate a `size`-byte block **without writing anything**, recording it
    /// for rollback. The caller supplies the block's bytes later via
    /// [`write`](Self::write). The allocator's owned-slice handle is not RAII, so
    /// letting it drop here does not free the block.
    pub fn alloc_raw<A: BStackOwnedSliceAllocator>(
        &mut self,
        allocator: &A,
        size: u64,
    ) -> io::Result<BStackRange> {
        let slice = allocator.alloc(size)?;
        let range = slice.as_range();
        self.allocated.push(range);
        Ok(range)
    }

    /// Record a pending in-place write of `bytes` at absolute `offset`.
    pub fn write(&mut self, offset: u64, bytes: Vec<u8>) {
        self.writes.push((offset, bytes));
    }

    /// Register an already-allocated range for rollback — for allocations made
    /// outside [`alloc_raw`](Self::alloc_raw) (e.g. a vector data block built and
    /// written eagerly by the vector runtime, whose bytes are committed on
    /// creation rather than staged in [`write`](Self::write)).
    pub fn track_alloc(&mut self, range: BStackRange) {
        self.allocated.push(range);
    }

    /// Record that the strong count of a shared child at `data` must be bumped by
    /// one — the strong reference this clone's `#[bstack_strong]` field acquires.
    pub fn bump_strong<T: BStackShared, A: BStackOwnedSliceAllocator>(
        &mut self,
        data: BStackRef<T>,
        allocator: &A,
    ) -> io::Result<()> {
        let (data_ref, ctrl) = T::strong_parts(data, allocator)?;
        let off = match ctrl {
            None => data_ref.into_range().start() + layout::RC_REFCOUNT_OFFSET,
            Some(c) => c.start() + layout::CTRL_STRONG_OFFSET,
        };
        self.bumps.push(off);
        Ok(())
    }

    /// Record that the weak count of the control block at `ctrl_off` must be
    /// bumped by one — the weak reference this clone's `#[bstack_weak]` field
    /// acquires.
    pub fn bump_weak(&mut self, ctrl_off: u64) {
        self.bumps.push(ctrl_off + layout::CTRL_WEAK_OFFSET);
    }

    /// Free everything allocated so far, in reverse order. The error path, taken
    /// when planning fails before [`commit`](Self::commit).
    pub fn rollback<A: BStackOwnedSliceAllocator>(self, allocator: &A) {
        Self::free_all(self.allocated, allocator);
    }

    /// Apply the refcount bumps, then commit every pending write as one
    /// crash-atomic batch. On any failure, undoes the applied bumps and frees the
    /// allocations before propagating.
    pub fn commit<A: BStackOwnedSliceAllocator>(self, allocator: &A) -> io::Result<()> {
        let stack = allocator.stack();
        // Phase 2a: refcount bumps (each atomic on its own counter).
        let mut applied = 0usize;
        for &off in &self.bumps {
            if let Err(e) = refcount::fetch_add(stack, off, 1) {
                self.unwind(applied, allocator);
                return Err(e);
            }
            applied += 1;
        }
        // Phase 2b: one crash-atomic batch of all block payloads. The new blocks
        // are distinct ranges, so `set_batched`'s no-overlap rule always holds.
        if let Err(e) = stack.set_batched(self.writes.iter().map(|(o, d)| (*o, d.as_slice()))) {
            self.unwind(applied, allocator);
            return Err(e);
        }
        Ok(())
    }

    /// Undo the first `applied` bumps and free every allocation. Shared error
    /// path for [`commit`](Self::commit).
    fn unwind<A: BStackOwnedSliceAllocator>(self, applied: usize, allocator: &A) {
        let stack = allocator.stack();
        for &off in &self.bumps[..applied] {
            let _ = refcount::fetch_sub(stack, off, 1);
        }
        Self::free_all(self.allocated, allocator);
    }

    fn free_all<A: BStackOwnedSliceAllocator>(allocated: Vec<BStackRange>, allocator: &A) {
        for r in allocated.into_iter().rev() {
            // SAFETY: each range was returned by our own `alloc_raw` and never
            // handed to another owner, so freeing it here is sound.
            let _ = unsafe { dealloc_range(allocator, r) };
        }
    }
}
