//! # `bstack_raii`
//!
//! A typed, RAII-style ownership, lifetime, and on-disk-layout layer built on
//! top of the mainline `bstack` `alloc` primitives ([`bstack::BStackRange`],
//! [`bstack::BStackSlice`], [`bstack::BStackOwnedSlice`]). It decouples
//! disk-level destruction ([`BStackDrop`]) from Rust's process-scoped `Drop`,
//! providing persistent-storage ownership with C++-style `unique_ptr` /
//! `shared_ptr` / `weak_ptr` conveniences.
//!
//! The full design lives in `RAII.md` at the repository root. This crate is its
//! implementation. It is a separate crate (not a `bstack` feature) so that its
//! large, not-yet-stable ABI surface never gates `bstack`'s ABI stability.
//!
//! ## Module map (bottom-up)
//!
//! | Module         | Contents                                                    |
//! |----------------|-------------------------------------------------------------|
//! | [`layout`]     | On-disk primitives: [`EightCC`], [`BlockHeader`] (both Pod). |
//! | [`reference`]  | [`BStackRef`]: typed range wrapper + buffered `OnDisk` read. |
//! | [`teardown`]   | [`BStackDrop`] trait, [`AutoDrop`] RAII guard, [`dealloc_range`]. |
//! | [`block`]      | Block-type contracts: [`BStackCast`], [`BStackBlock`], [`BStackWeakable`]. |
//! | [`refcount`]   | Little-endian atomic CAS ops over on-disk `u64` counters.    |
//! | [`clone`]      | [`TryClone`]: fallible clone for handles that touch disk.    |
//! | [`handle`]     | Without-allocator inner handles: [`OwnedRef`], [`StrongRef`], [`StrongWeakRef`], [`WeakRef`]. |
//! | [`owned`]      | [`BStackOwned`]: the without-allocator, uniquely-owned block handle. |
//! | [`shared`]     | [`BStackRc`] + [`BStackWeak`]: with-allocator shared handles.|
//!
//! ## Conventions fixed by the ABI
//!
//! * All on-disk multi-byte integers (refcounts, offsets) are **little-endian**,
//!   matching `bstack`'s own on-disk format.
//! * Reads are **buffer-based** (`read_into` + `bytemuck::from_bytes`); there is
//!   no zero-copy path without `mmap`.
//! * The whole layer speaks [`std::io::Result`] / [`std::io::Error`], a
//!   consequence of binding allocators to [`bstack::BStackOwnedSliceAllocator`]
//!   (which pins `Error = io::Error` and `Allocated<'a> = BStackOwnedSlice`).
//!
//! ## Status
//!
//! Types and traits are laid out with their final signatures; method bodies
//! marked `todo!()` are the work ahead. Procedural macros
//! ([`macro@bstack_block`], [`bstack_move`], [`bstack_cast`]) come after the
//! runtime is filled in.

#![allow(dead_code, unused_imports, unused_variables)]

// Lets code generated by `#[bstack_block]` reference this crate as
// `::bstack_raii::…` even from within the crate's own tests.
extern crate self as bstack_raii;

mod block;
mod cast;
mod clone;
mod construct;
mod handle;
mod layout;
mod owned;
mod refcount;
mod reference;
mod shared;
mod teardown;
mod vec;

#[cfg(test)]
mod tests;

pub use block::{
    BStackBlock, BStackCast, BStackMove, BStackMoveExpr, BStackShared, BStackWeakable,
};
pub use cast::{BStackCastAs, BStackCastInto};
pub use clone::TryClone;
pub use construct::{alloc_block, alloc_control, init_rc, set_weak_field, upgrade_weak_field};
pub use handle::{OwnedRef, StrongRef, StrongWeakRef, WeakRef};
pub use layout::{BlockHeader, EightCC};
pub use owned::BStackOwned;
pub use reference::BStackRef;
pub use shared::{BStackRc, BStackWeak};
pub use teardown::{AutoDrop, BStackDrop, dealloc_range};
pub use vec::{BStackBlockVec, BStackRefVec, BStackStrongVec, BStackVec, BStackWeakVec, VecDesc};

// Re-exports for use by `#[bstack_block]`-generated code (and callers), so that
// generated code can name everything through `::bstack_raii::…` and downstream
// crates need not depend on `bstack` or `bytemuck` directly.
pub use bstack::{BStack, BStackAllocator, BStackOwnedSliceAllocator, BStackRange, BStackSlice};
pub use bytemuck::{Pod, Zeroable};
// Re-exported whole so generated code can call `::bstack_raii::bytemuck::bytes_of`.
pub use bytemuck;

// Procedural macros, re-exported so downstream depends only on `bstack_raii`.
pub use bstack_raii_derive::{bstack_block, bstack_cast, bstack_enum, bstack_move};

/// `compile_fail` checks for illegal macro inputs. Each block must **fail** to
/// compile; the accompanying comment says why.
///
/// An ownership annotation is only allowed on a **single-field tuple** variant; a
/// unit, struct, or multi-field tuple variant is a POD aggregate that rejects
/// annotations.
///
/// `#[bstack_ref]` on a **unit** variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_ref] Unit }
/// # fn main() {}
/// ```
///
/// `#[bstack_ref]` on a **struct** variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_ref] S { a: u32, b: u32 } }
/// # fn main() {}
/// ```
///
/// `#[bstack_strong]` on a **multi-field tuple** variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_strong] T(u32, i8) }
/// # fn main() {}
/// ```
///
/// **Two** ownership annotations on one variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_owned] #[bstack_ref] V(u32) }
/// # fn main() {}
/// ```
///
/// **Duplicate discriminant** values (rustc's `E0081` can't fire — the macro
/// replaces the enum — so the macro rejects it itself):
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { A = 1, B = 1 }
/// # fn main() {}
/// ```
///
/// A discriminant **out of range** for the chosen `repr`:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(repr(u8))]
/// enum E { A = 300 }
/// # fn main() {}
/// ```
///
/// `repr(usize)` / `repr(isize)` (bstack offsets are 64-bit):
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(repr(usize))]
/// enum E { A }
/// # fn main() {}
/// ```
///
/// An unsupported `repr` width:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(repr(u128))]
/// enum E { A }
/// # fn main() {}
/// ```
///
/// A **generic** enum:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E<T> { A(T) }
/// # fn main() {}
/// ```
///
/// `weak` without `rc`:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(weak)]
/// enum E { A }
/// # fn main() {}
/// ```
///
/// A **non-`Pod`** field in a POD aggregate variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { V(String) }
/// # fn main() {}
/// ```
///
/// An ownership annotation targeting a **non-block** type:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_owned] V(u32) }
/// # fn main() {}
/// ```
///
/// `repr(..)` on a **struct** (it selects an enum discriminant width):
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block(repr(u64))]
/// struct X { a: u32 }
/// # fn main() {}
/// ```
#[doc(hidden)]
pub mod __macro_compile_fail_tests {}
