//! # `bstack_raii`
//!
//! A typed, RAII-style ownership, lifetime, and on-disk-layout layer built on
//! top of the mainline `bstack` `alloc` primitives ([`bstack::BStackRange`],
//! [`bstack::BStackSlice`], [`bstack::BStackOwnedSlice`]). It decouples
//! disk-level destruction ([`BStackDrop`]) from Rust's process-scoped `Drop`,
//! providing persistent-storage ownership with C++-style `unique_ptr` /
//! `shared_ptr` / `weak_ptr` conveniences.
//!
//! The full design lives in `RAII.md` at the repository root. This crate is its
//! implementation. It is a separate crate (not a `bstack` feature) so that its
//! large, not-yet-stable ABI surface never gates `bstack`'s ABI stability.
//!
//! ## Module map (bottom-up)
//!
//! | Module         | Contents                                                    |
//! |----------------|-------------------------------------------------------------|
//! | [`layout`]     | On-disk primitives: [`EightCC`], [`BlockHeader`] (both Pod). |
//! | [`reference`]  | [`BStackRef`]: typed range wrapper + buffered `OnDisk` read. |
//! | [`teardown`]   | [`BStackDrop`] trait, [`AutoDrop`] RAII guard, [`dealloc_range`]. |
//! | `construct`    | Block creation: allocate, stamp the header, wire refcounts / control blocks — the build-side counterpart to `teardown`. |
//! | [`block`]      | Block-type contracts: [`BStackCast`], [`BStackBlock`], [`BStackWeakable`]. |
//! | [`refcount`]   | Little-endian atomic CAS ops over on-disk `u64` counters.    |
//! | `bulk`         | Sequential fallbacks for [`BStackRaiiAllocator::alloc_many`] / [`free_many`](BStackRaiiAllocator::free_many); bulk allocators override those trait methods. |
//! | [`clone`]      | [`TryClone`] / [`TryCloneIn`]: fallible clone for handles that touch disk. |
//! | [`handle`]     | Without-allocator inner handles: [`OwnedRef`], [`StrongRef`], [`StrongWeakRef`], [`WeakRef`]. |
//! | [`owned`]      | [`BStackOwned`]: the without-allocator, uniquely-owned block handle. |
//! | [`shared`]     | [`BStackRc`] + [`BStackWeak`]: with-allocator shared handles.|
//! | `cast`         | Typed ↔ untyped handle conversion — the runtime behind `bstack_cast!`. |
//! | `vec`          | [`VecDesc`]-backed growable vectors reached through a fixed-size field. |
//! | [`replace`]    | [`ReplaceError`]: the error a generated `replace_<field>` mutator returns. |
//! | [`registry`]   | Process-wide path↔[`FileId`](registry::FileId) registry underlying `Foreign<T>`. |
//! | `foreign`      | [`Foreign<T>`]: a cross-file pointer (file identity + offset).|
//! | `wal`          | Write-ahead log for atomic multi-slice transactions and leak reclamation. |
//! | `stdlib`       | Ergonomic handle/collection types built entirely on the above (e.g. [`BStackHashMap`], [`BStackDeque`], [`BStackCow`]). |
//!
//! ## Conventions fixed by the ABI
//!
//! * All on-disk multi-byte integers (refcounts, offsets) are **little-endian**,
//!   matching `bstack`'s own on-disk format.
//! * Reads are **buffer-based** (`read_into` + `bytemuck::from_bytes`); there is
//!   no zero-copy path without `mmap`.
//! * The whole layer speaks [`std::io::Result`] / [`std::io::Error`], a
//!   consequence of binding allocators to [`bstack::BStackOwnedSliceAllocator`]
//!   (which pins `Error = io::Error` and `Allocated<'a> = BStackOwnedSlice`).
//!
//! ## Status
//!
//! Feature-complete: the runtime primitives, the procedural macros
//! ([`macro@bstack_block`], [`macro@bstack_enum`], [`bstack_move`],
//! [`bstack_cast`]), and the [`stdlib`] collection suite are all implemented and
//! exercised by the test suite. The main open gap is `Foreign<T>` cross-file
//! deep-clone/teardown dispatch, which is still deferred (a `Foreign` field is
//! byte-copied on clone and freed by nobody on teardown regardless of its
//! ownership annotation) — see the [`foreign`] module docs.

// Lets code generated by `#[bstack_block]` reference this crate as
// `::bstack_raii::…` even from within the crate's own tests.
extern crate self as bstack_raii;

mod block;
mod bulk;
mod cast;
mod clone;
mod construct;
mod foreign;
mod handle;
mod layout;
mod owned;
mod refcount;
mod reference;
/// Cross-file `Foreign<T>` support: the process-wide path↔id file registry.
pub mod registry;
mod replace;
mod shared;
mod stdlib;
mod teardown;
mod vec;
mod wal;

#[cfg(test)]
mod tests;

pub use block::{
    BStackBlock, BStackCast, BStackMove, BStackMoveExpr, BStackShared, BStackWeakable,
};
pub use cast::{BStackCastAs, BStackCastInto};
pub use clone::{ClonePlan, TryClone, TryCloneIn};
pub use construct::{alloc_block, build_control_payload, set_weak_field, upgrade_weak_field};
pub use foreign::Foreign;
/// The inert on-disk wire form of a [`Foreign`] pointer. Not part of the public API —
/// generated `#[bstack_block]` code names it through `::bstack_raii::ForeignRepr`; user
/// code should never use it directly.
#[doc(hidden)]
pub use foreign::ForeignRepr;
pub use handle::{OwnedRef, StrongRef, StrongWeakRef, WeakRef};
pub use layout::{BlockHeader, EightCC, get_u64};
pub use owned::BStackOwned;
pub use reference::BStackRef;
pub use registry::ForeignHostAllocator;
pub use replace::ReplaceError;
pub use shared::{BStackRc, BStackWeak};
pub use stdlib::{
    BStackBTreeMap, BStackBTreeSet, BStackBinaryHeap, BStackBox, BStackCountingBloomFilter,
    BStackCow, BStackDeque, BStackHashMap, BStackHashSet, BStackLinkedList, BStackString,
    BTreeMapIter, BTreeSetIter, BloomOnDisk, BoxOnDisk, DequeIter, DequeOnDisk, HashMapIter,
    HashSetIter, HashSetOnDisk, HeapOnDisk, ListIter, ListOnDisk, MapOnDisk, NodeOnDisk,
    StringOnDisk, TreeOnDisk, TreeSetOnDisk,
};
pub use teardown::{AutoDrop, BStackDrop, dealloc_range, wal_teardown};
pub use vec::{BStackBlockVec, BStackRefVec, BStackStrongVec, BStackVec, BStackWeakVec, VecDesc};
pub use wal::{STD_WAL_ANCHOR, finish};

// Re-exports for use by `#[bstack_block]`-generated code (and callers), so that
// generated code can name everything through `::bstack_raii::…` and downstream
// crates need not depend on `bstack` or `bytemuck` directly.
pub use bstack::{BStack, BStackAllocator, BStackOwnedSliceAllocator, BStackRange, BStackSlice};
pub use bytemuck::{Pod, Zeroable};

/// The allocator every `bstack_raii` operation is bound on: a
/// [`BStackOwnedSliceAllocator`] the layer can soundly build owning handles on top
/// of. It is the crate-wide allocator capability — constructors, `try_clone_in`,
/// `bstack_drop`, and every stdlib collection require it.
///
/// Beyond its supertrait it carries two things the layer relies on: the **null
/// niche** at payload offset 0 (a hard safety requirement, see below) and an
/// **optional** WAL anchor slot. The anchor is what lets `try_clone_in` /
/// `bstack_drop` reclaim orphaned allocations on the next open **automatically**
/// (they read [`wal_anchor`](Self::wal_anchor) directly); `None` (the default)
/// means "no reclamation" — those ops behave exactly as before, minus the
/// crash-orphan cleanup. Every bstack-provided allocator implements this trait; a
/// custom allocator that upholds the null niche adds a one-line
/// `unsafe impl BStackRaiiAllocator for MyAlloc {}` (defaulting to `None`, or
/// returning `Some(slot)` if it reserves a stable slot).
///
/// The WAL machinery it feeds lives in the `wal` module; the trait itself is the
/// crate's front-door allocator bound, hence its home here at the root.
///
/// # Safety
///
/// An implementor asserts **both** of the following:
///
/// 1. **Null niche.** The allocator **never** hands out a live slice whose
///    `start()` is `0`. `bstack_raii` reserves payload offset 0 as its universal
///    null sentinel — a `0` offset means "none" everywhere in the layer (an absent
///    handle / [`Option`] niche, a dead weak reference, "no WAL block", …). An
///    allocator that could return offset 0 is **unsound** with this crate: a real
///    allocation would be indistinguishable from null. (Every bstack allocator
///    satisfies this: each keeps a reserved region at payload offset 0 that it
///    never allocates from.)
///
/// 2. **WAL anchor (only when returning `Some(off)`).** `[off, off + 8)` is a
///    stable, persistent 8-byte region the allocator **never** hands out via
///    `alloc` and **never** uses for its own metadata, and that survives across
///    open/close. `bstack_raii` stores the current WAL block's offset there
///    (`0` = none). Returning `None` asserts nothing beyond (1).
pub unsafe trait BStackRaiiAllocator: BStackOwnedSliceAllocator {
    fn wal_anchor(&self) -> Option<u64> {
        None
    }

    /// The [`FileId`](crate::registry::FileId) whose file this allocator's frees
    /// belong to, used to **tag WAL teardown entries**. A normal file-owning
    /// allocator represents *its own* file, so it returns [`FileId::SELF`](crate::registry::FileId::SELF)
    /// (`0`) — its WAL entries mean "this file". The cross-file teardown adapter
    /// [`ForeignHostAllocator`](crate::registry::ForeignHostAllocator) overrides this
    /// with the foreign file's id, so a free collected while tearing down a foreign
    /// subtree is recorded against — and, on recovery, reclaimed in — *that* file
    /// (see [`crate::wal`]'s `free_recorded`). Callers other than the teardown WAL
    /// have no reason to read this.
    fn wal_file_id(&self) -> crate::registry::FileId {
        crate::registry::FileId::SELF
    }

    /// Allocate one block per length in `sizes`, returning their ranges in order.
    ///
    /// The default is a **sequential** fallback: each `alloc` is individually
    /// crash-atomic, but the set is not (a crash mid-sequence orphans the blocks
    /// done so far — a leak the WAL layer reclaims, never a torn structure). It
    /// unwinds already-allocated blocks on any failure, so a partial allocation
    /// never leaks *within* the call.
    ///
    /// A bulk-capable allocator ([`bstack::BStackBulkAllocator`]) **overrides** this
    /// to route through the atomic [`alloc_bulk`](bstack::BStackBulkAllocator::alloc_bulk),
    /// so the whole set becomes one crash-atomic operation recovered by the
    /// allocator's own machinery. Ordinary trait dispatch picks the override at
    /// monomorphization, so compound ops generic over `A` get the fast path for free.
    fn alloc_many(&self, sizes: &[u64]) -> std::io::Result<Vec<BStackRange>> {
        crate::bulk::seq_alloc_many(self, sizes)
    }

    /// Free every range in `ranges`. The default is a **sequential** fallback
    /// (each `dealloc` individually atomic); a bulk-capable allocator overrides it
    /// to route through the atomic [`dealloc_bulk`](bstack::BStackBulkAllocator::dealloc_bulk).
    ///
    /// # Safety-adjacent contract
    /// Each range must be a live allocation owned by `self` that no other live
    /// handle will also free (as for [`crate::teardown`]'s `dealloc_range`).
    fn free_many(&self, ranges: impl IntoIterator<Item = BStackRange>) -> std::io::Result<()> {
        crate::bulk::seq_free_many(self, ranges)
    }

    /// Whether this allocator provides **atomic, self-recovering** bulk
    /// alloc/free — i.e. it implements [`bstack::BStackBulkAllocator`] and
    /// overrides [`alloc_many`](Self::alloc_many) / [`free_many`](Self::free_many)
    /// to route through it. Default `false`.
    ///
    /// When `true`, a compound op whose blocks all live in **this** file can free
    /// (or allocate) them as one atomic `dealloc_bulk` / `alloc_bulk` and **skip the
    /// WAL** entirely: the WAL exists to emulate atomic batch alloc/free for
    /// allocators that lack it, and wrapping an already-atomic bulk op in it is both
    /// redundant and unsound (the allocator's crash-recovery direction is opaque, so
    /// a WAL retry on reopen could double-free). A crash mid-bulk is left to the
    /// allocator's own recovery — consistent, leak-at-worst, exactly the guarantee
    /// the WAL would have provided. Cross-file (mixed [`FileId`](crate::registry::FileId))
    /// batches fall back to the WAL for its registry routing.
    fn atomic_bulk(&self) -> bool {
        false
    }
}
// Re-exported whole so generated code can call `::bstack_raii::bytemuck::bytes_of`.
pub use bytemuck;

// Procedural macros, re-exported so downstream depends only on `bstack_raii`.
pub use bstack_raii_derive::{bstack_block, bstack_cast, bstack_enum, bstack_move};

/// Runtime support called by `#[bstack_block]` / `#[bstack_enum]`-generated code via
/// fully-qualified `::bstack_raii::__private::…` paths. Not part of the public API —
/// no stability guarantee, use directly at your own risk.
#[doc(hidden)]
pub mod __private {
    pub use crate::foreign::{
        foreign_clone_owned, foreign_clone_strong, foreign_clone_weak, foreign_drop_owned,
        foreign_drop_strong, foreign_drop_weak,
    };
}

/// `compile_fail` checks for illegal macro inputs. Each block must **fail** to
/// compile; the accompanying comment says why.
///
/// An ownership annotation is only allowed on a **single-field tuple** variant; a
/// unit, struct, or multi-field tuple variant is a POD aggregate that rejects
/// annotations.
///
/// `#[bstack_ref]` on a **unit** variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_ref] Unit }
/// # fn main() {}
/// ```
///
/// `#[bstack_ref]` on a **struct** variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_ref] S { a: u32, b: u32 } }
/// # fn main() {}
/// ```
///
/// `#[bstack_strong]` on a **multi-field tuple** variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_strong] T(u32, i8) }
/// # fn main() {}
/// ```
///
/// **Two** ownership annotations on one variant:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_owned] #[bstack_ref] V(u32) }
/// # fn main() {}
/// ```
///
/// **Duplicate discriminant** values (rustc's `E0081` can't fire — the macro
/// replaces the enum — so the macro rejects it itself):
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { A = 1, B = 1 }
/// # fn main() {}
/// ```
///
/// A discriminant **out of range** for the chosen `repr`:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(repr(u8))]
/// enum E { A = 300 }
/// # fn main() {}
/// ```
///
/// `repr(usize)` / `repr(isize)` (bstack offsets are 64-bit):
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(repr(usize))]
/// enum E { A }
/// # fn main() {}
/// ```
///
/// An unsupported `repr` width:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(repr(u128))]
/// enum E { A }
/// # fn main() {}
/// ```
///
/// A **generic** enum:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E<T> { A(T) }
/// # fn main() {}
/// ```
///
/// `weak` without `rc`:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum(weak)]
/// enum E { A }
/// # fn main() {}
/// ```
///
/// An ownership annotation targeting a **non-block** type:
/// ```compile_fail
/// use bstack_raii::bstack_enum;
/// #[bstack_enum]
/// enum E { #[bstack_owned] V(u32) }
/// # fn main() {}
/// ```
///
/// `repr(..)` on a **struct** (it selects an enum discriminant width):
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block(repr(u64))]
/// struct X { a: u32 }
/// # fn main() {}
/// ```
///
/// ---
///
/// The same shapes on `#[bstack_block]` **structs**.
///
/// **Two** ownership annotations on one field:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct X { #[bstack_owned] #[bstack_ref] f: u32 }
/// # fn main() {}
/// ```
///
/// An ownership annotation targeting a **non-block** type — including a generic
/// wrapper like `Wrapper<Foo<Bar>>` (an on-disk ref is not generic), even when
/// the type would be fine stored inline as POD *without* the annotation:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct X { #[bstack_owned] f: core::num::Wrapping<u32> }
/// # fn main() {}
/// ```
///
/// A `#[bstack_weak]` field whose target isn't weak-observable:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct X { #[bstack_weak] f: u32 }
/// # fn main() {}
/// ```
///
/// An un-annotated **non-`Pod`** field:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// struct NotPod(String);
/// #[bstack_block]
/// struct X { f: NotPod }
/// # fn main() {}
/// ```
///
/// `weak` without `rc`:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block(weak)]
/// struct X { f: u32 }
/// # fn main() {}
/// ```
///
/// ---
///
/// Misuse of `#[embed]` (which inlines a whole child *block*).
///
/// `#[embed]` on a **non-block** type:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct X { #[embed] f: u32 }
/// # fn main() {}
/// ```
///
/// `#[embed]` on a **tuple**:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct X { #[embed] f: (u8, u8) }
/// # fn main() {}
/// ```
///
/// `#[embed]` wrapped in `Option`:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct X { #[embed] f: Option<u32> }
/// # fn main() {}
/// ```
///
/// `#[embed]` combined with another ownership annotation:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct X { #[embed] #[bstack_owned] f: u32 }
/// # fn main() {}
/// ```
///
/// (Tuple structs of POD fields and unit structs are **valid**, not errors — see
/// the tests.)
///
/// ---
///
/// A **shared** (`rc` / `rc, weak`) block has no `TryCloneIn`: it is cloned by
/// duplicating its handle (a refcount bump) via `BStackRc::try_clone`, not
/// deep-copied to an owned block, so `try_clone_in` on one is a compile error:
/// ```compile_fail
/// use bstack_raii::{bstack_block, BStackOwnedSliceAllocator, TryCloneIn};
/// #[bstack_block(rc)]
/// struct S { v: u32 }
/// fn f<A: BStackOwnedSliceAllocator>(s: &S, a: &A) {
///     let _ = s.try_clone_in(a); // no such method on a shared block
/// }
/// # fn main() {}
/// ```
///
/// ---
///
/// A **bare** `Foreign<T>` field (no ownership annotation): a foreign pointer must
/// name its target's kind, like an in-file reference:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { link: Foreign<Leaf> }
/// # fn main() {}
/// ```
///
/// `Foreign<T>` where `T` is **not a bstack block** (`Foreign<Pod>`):
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: bstack_raii::Foreign<u32> }
/// # fn main() {}
/// ```
///
/// `Foreign<Option<T>>` — a nullable foreign pointer is `Option<Foreign<T>>`:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: Foreign<Option<Leaf>> }
/// # fn main() {}
/// ```
///
/// **No double `Foreign`** (`Foreign<Foreign<T>>`) — a pointer to a pointer; bridge
/// with a `#[bstack_block]` struct:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: Foreign<Foreign<Leaf>> }
/// # fn main() {}
/// ```
///
/// **No double `Foreign` through `Option`** (`Foreign<Option<Foreign<T>>>`):
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: Foreign<Option<Foreign<Leaf>>> }
/// # fn main() {}
/// ```
///
/// **No pointer to a `Vec`** (`Foreign<Vec<T>>`) — `Vec<Foreign<T>>` is the allowed
/// form (a vector OF pointers); a pointer TO a vector must be bridged:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: Foreign<Vec<Leaf>> }
/// # fn main() {}
/// ```
///
/// **No pointer to an array** (`Foreign<[T; N]>`) — `[Foreign<T>; N]` is allowed:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: Foreign<[Leaf; 4]> }
/// # fn main() {}
/// ```
///
/// **No pointer to a tuple** (`Foreign<(A, B)>`):
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: Foreign<(Leaf, Leaf)> }
/// # fn main() {}
/// ```
///
/// **No pointer to a `String`** (`Foreign<String>`):
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block]
/// struct Holder { #[bstack_owned] link: bstack_raii::Foreign<String> }
/// # fn main() {}
/// ```
///
/// The bad target also applies **inside a container** — e.g. a `Vec` of double
/// foreigns (`Vec<Foreign<Foreign<T>>>`) is rejected the same way:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] links: Vec<Foreign<Foreign<Leaf>>> }
/// # fn main() {}
/// ```
///
/// **`Foreign` inside a tuple inside a `Vec`** (`Vec<(_, Foreign<T>)>`) — a foreign
/// *tuple* field is allowed, but not as a `Vec` element:
/// ```compile_fail
/// use bstack_raii::bstack_block;
/// #[bstack_block] struct Leaf { v: u32 }
/// #[bstack_block]
/// struct Holder { #[bstack_owned] v: Vec<(u32, Foreign<Leaf>)> }
/// # fn main() {}
/// ```
#[doc(hidden)]
pub mod __macro_compile_fail_tests {}
